woowacourse-teams/2024-ody

android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
android/app/src/main/res/values/strings.xml

feat: 알림 권한 요청

---

backend/src/main/java/com/ody/common/annotation/FutureOrPresentDateTime.java
backend/src/main/java/com/ody/common/validator/FutureOrPresentDateTimeValidator.java
backend/src/main/java/com/ody/mate/domain/Mate.java
backend/src/main/java/com/ody/mate/domain/NickName.java
backend/src/main/java/com/ody/meeting/controller/MeetingController.java
backend/src/main/java/com/ody/meeting/domain/Location.java
backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequest.java
backend/src/test/java/com/ody/common/validator/FutureOrPresentDateTimeValidatorTest.java
backend/src/test/java/com/ody/mate/domain/NickNameTest.java
backend/src/test/java/com/ody/meeting/domain/LocationTest.java

close #58 
<br>
모임 정보 입력 검증 로직 추가. 
◦ 모임 이름은 1자 이상, 16자 미만이다.
->DTO에서 validation 어노테이션으로 처리
◦ 모임 날짜, 시간은 개설 시점 이전일 수 없다. 
-> DTO에서 커스텀 validation으로 처리
(현재 날짜와 시간이 분리되어 있는 상황에서 날짜가 오늘이면서 현재시간 이후인지에 대한 검증이 힘들어 `FutureOrPresentDateTime` 커스텀 어노테이션으로 해결)
◦ 모임 장소는 수도권(서울, 경기도, 인천) 내에 있어야 한다.
-> Location 도메인 내부에서 지역이름으로 검증
• 닉네임은 1자 이상, 10자 미만이다.
->DTO에서 validation 어노테이션으로 처리
<br>
<br>
> 닉네임 검증을 값 객체 사용
닉네임의 경우에는 약속 방을 개설한 사람, 약속 방에 참여한 사람들 모두 검증이 필요한데
`MeetingSaveRequest`, `MateSaveRequest`에서 validation 어노테이션으로 중복 검증을 하는 것 보다
NickName 값 객체로 분리해 공통화 시키는게 좋을 것 같은데 어떻게 생각하시나요 ?

feat: 모임 정보 입력 검증 로직 추가

---

android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoViewModel.kt
android/app/src/main/java/com/woowacourse/ody/presentation/nickname/JoinNickNameFragment.kt
android/app/src/main/java/com/woowacourse/ody/util/CommonBindingAdapter.kt
android/app/src/main/res/drawable/ic_cancel.xml
android/app/src/main/res/layout/fragment_join_nickname.xml
android/app/src/main/res/values/strings.xml

close #26 
<br>
<br>
https://github.com/user-attachments/assets/0b845f0b-7200-41a8-8510-9685fd93777e
<br>
- 엑스 버튼 클릭 리스너는 뷰모델 함수로 구현할 수 있어서, 따로 리스너 인터페이스를 만들지 않았습니다. 어차피 xml에는 뷰모델 전체를 전달하기 때문에 인터페이스로 구현해도 동일해질 것 같아서요... 이 경우에도 인터페이스 구현하는 것을 선호하시나요 다들??
- 현재 키보드가 올라오면 하단 다음 버튼이 보이지 않습니다. 이거 adjustResize 속성만 지정하면 되는 거같은데 추후에 해보겠습니다 ㅜ 잘 안됨

feat: 닉네임 입력 화면 구현

---

backend/src/main/java/com/ody/mate/domain/Mate.java
backend/src/main/java/com/ody/mate/repository/MateRepository.java
backend/src/main/java/com/ody/mate/service/MateService.java
backend/src/main/java/com/ody/member/domain/DeviceToken.java
backend/src/main/java/com/ody/member/domain/Member.java
backend/src/main/java/com/ody/member/repository/MemberRepository.java
backend/src/main/java/com/ody/member/service/MemberService.java
backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
backend/src/test/java/com/ody/member/repository/MemberRepositoryTest.java

#121 가 merge 되기 전에, 먼저 merge 해야 합니다!
close #120 
<br>
<details><summary>참고</summary>
</details>
<br>

fix: 회원 생성, 모임 참여 API 오류 수정

---

android/app/build.gradle.kts
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/woowacourse/ody/data/local/FCMService.kt
android/app/src/main/java/com/woowacourse/ody/data/remote/FCMService.kt
android/app/src/main/res/values/strings.xml
android/gradle/libs.versions.toml

close #30
<br>
<br>
https://github.com/user-attachments/assets/bd68bfa9-6ed7-4fc7-b2e9-ce1f45beba77
영상은 7초에 시작입니다.
<br>
FCMService에 모든 기능을 때려넣는게 그다지 올바른 구현은 아니겠지만,
좋은 구조 생각나지 않아 일단 이대로 올립니다.
FCMService를 data 계층에, Notification 기능을 presenter 계층에 두고,
repository를 통해 호출하는 그런 구조를 생각하고 삽질 조금 하다가, 그냥 날리고 PR 올립니다.
테스트는 postman을 이용했습니다.

feat: Notification 구현

---

backend/src/main/java/com/ody/notification/service/FcmPushSender.java
backend/src/main/java/com/ody/notification/service/FcmSubscriber.java
backend/src/main/java/com/ody/notification/service/NotificationService.java

close #150 
<br>
FCM 토픽 Malformed topic name 에러 해결
```
2024-07-25T16:13:00.000+09:00 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
java.lang.IllegalArgumentException: Malformed topic name
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar!/:na]
at com.google.firebase.messaging.Message.stripPrefix(Message.java:149) ~[firebase-admin-9.2.0.jar!/:na]
at com.google.firebase.messaging.Message.<init>(Message.java:82) ~[firebase-admin-9.2.0.jar!/:na]
at com.google.firebase.messaging.Message.<init>(Message.java:40) ~[firebase-admin-9.2.0.jar!/:na]
at com.google.firebase.messaging.Message$Builder.build(Message.java:295) ~[firebase-admin-9.2.0.jar!/:na]
at …
```

fix: FCM 토픽 Malformed topic name 에러 해결

---

backend/src/main/java/com/ody/mate/controller/MateController.java
backend/src/main/java/com/ody/mate/controller/MateControllerSwagger.java
backend/src/main/java/com/ody/mate/dto/request/MateSaveRequest.java
backend/src/main/java/com/ody/meeting/dto/response/MateResponse.java
backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponse.java
backend/src/main/java/com/ody/swagger/annotation/ErrorCode404.java

close #231 
<br>
- 404에러도 커스텀 어노테이션으로 description 옵션만 변경하여 에러 메세지가 다르게 표시되도록 적용
- /v1/mates API 문서화
<br>
<br>
- /mates 요청 메서드는 살리되 문서에선 헷갈릴 여지가 충분할것 같아 추가하지않았습니다. /mates가 지원중단으로 표시되어 있는데 지원 중단인 메서드들은 기존 컨트롤러에서도 제거하는게 어떠신가요?
<br>
- 404에러도 커스텀 어노테이션을 추가해 문서 작업을 할 때 404에러도 해당 커스텀 에러로 나머지 커스텀 에러와 일관되게 간편히 처리되도록 하면 좋을 것 같아요
<br>
- 응답 DTO로는 `MateSaveResponse`가 응답되는게 적절하다고 생각한는데 현재 노션에서 수정된 v1 API 문서상에 있는 응답 데이터가 `MeetingSaveResponse`와 동일하네요. 
<br>
현재 개설하고 참여해 로그 화면을 보는 흐름이
/v1/meetings -> /v1/mates -> /meetings/{meetingId}/noti-log + /v1/meetings/{meetingId} 요청 순이 되는 것 같은데
맞나요 ?
맞다면 특히 mateCount와 mates 필드가 있는 의미가 없는 것 같아요
이부분 안드측과 얘기 후에 변경하면 좋을 것 같습니다

docs: 약속 참여 API 문서화

---

backend/src/main/java/com/ody/meeting/controller/MeetingController.java
backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponse.java
backend/src/main/java/com/ody/meeting/service/MeetingService.java

close #233 
<br>
임의로 수정한 부분이 있습니다. 리뷰하실 때 의견 부탁드립니다!
이유:
- 노션 API response 표에는 모임장 닉네임 필드가 있는데, 예시에는 없었습니다.
- meeting 테이블 내 모임장 관련 정보를 저장하지 않습니다.(현재 테이블 구조 상 조회할 수 없음)
이유:
- 잘못된 meetingId을 요청할 수 있습니다. 노션 API에 404 에러를 추가했습니다.

docs: 약속 단건 조회 API 문서화

---

backend/src/main/java/com/ody/mate/dto/response/MateSaveResponse.java
backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponse.java
backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponseV1.java
backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponse.java

close #269 
<br>
모든 API에 대한 호출 데이터의 시간 데이터가 초 제거 후 반환하도록 수정
<br>
<br>

fix: 시간 데이터 초 제거 후 반환하도록 수정

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/woowacourse/ody/presentation/FloatingButtonActivity.kt
android/app/src/main/java/com/woowacourse/ody/presentation/FloatingButtonListener.kt
android/app/src/main/res/layout/activity_meeting_list.xml

close #213 
<br>
<br>
[Screen_recording_20240806_160038.webm](https://github.com/user-attachments/assets/3908d7af-ab0c-41aa-bbf2-9983555e410a)
<br>
- 차람이 홈화면이랑 이어준다고 하셔서 스트링 추출은 안했습니다.

feat: 플로팅 버튼 화면 이동 구현

---

android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardActivity.kt
android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogActivity.kt
android/app/src/main/res/layout/activity_eta_dashboard.xml

close #295 
<br>
<br>
https://github.com/user-attachments/assets/7b0f095e-c0c6-4c4e-99ca-c9d151087f82
<br>
NotificationLog 화면의 툴바 코드와 유사합니다.
현재는 NotificationLog 화면의 툴바와 완전히 동일해서, NotificationLog 화면에서 Eta 화면으로 데이터를 전달하고 있습니다.
그런데 Intent로 데이터를 하나하나 전달하는 로직이 좀 번거롭게 느껴지네요.
동일한 툴바를 공유하는 `MeetingRoomActivity` 등을 만들어서 NotificationLog와 Eta 화면을 fragment로 보여주면 더 깔끔해질 것 같아요.
추후 이런 방식으로 리팩터링 해보면 어떨까요??????

feat: 현황 화면 툴바 리스너 등록

---

android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt

close #299 
<br>
<br>
https://github.com/user-attachments/assets/d3121870-ca17-49a5-b579-3c3f4c356738
<br>
finish 한줄로 해결되니까 pr 올리기도 머쓱하네요. ㅋㅋ;;

fix: 모임 참여 화면 flow 수정

---

android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogActivity.kt
android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MeetingDetailUiModel.kt
android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MeetingDetailUiModelMapper.kt
android/app/src/main/res/layout/activity_notification_log.xml

feat: 로그에서 30분전이면 오디 버튼이 아예 안뜨게 구현

---

backend/src/main/java/com/ody/meeting/domain/Meeting.java
backend/src/main/java/com/ody/meeting/service/MeetingService.java
backend/src/test/java/com/ody/common/Fixture.java
backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java

close #289 
<br>
약속 시간이 현재 시간으로부터 24시간 이내인 약속부터 미래의 약속까지만 조회 가능하도록 필터링했습니다
<br>
<br>

feat: 내 약속 목록 조회 시 현재 이후 약속만 조회

---

backend/src/main/java/com/ody/eta/domain/Eta.java
backend/src/main/java/com/ody/eta/dto/response/MateEtaResponse.java
backend/src/test/java/com/ody/eta/domain/EtaTest.java

close #294 
<br>
- createAt 최초 저장 이후 변경 방지
- Missing 상태 일 시 -1 매직값이 반환되도록 추가
- EtaTest에서 isModified() 테스트 오류 수정
<br>
<br>
prePersist를 사용해서 LocalDateTime이 나노초가 제거되어 저장되도록 코드를 반영하려 했었는데
이 상황에서 Eta 도메인 테스트 작성시 데이터가 저장되어야지만 prePersist가 동작하는 문제가 있어
Eta 도메인 테스트가 Jpa에 의존적인 테스트가 되어 도메인 테스트임에도 불구하고 Bean들을 등록후 member, meeting, mate, eta들을 다 저장해서 테스트해야하는 문제가 있어 원래대로 롤백했어요
LocalDateTime 초를 제거하는 부분은 제리가 말했던데로 추후에 utill 클래스로 빼서 작업하면 좋을 듯한것 같습니다 🤔

fix: 행방불명상태의 소요시간 응답 오류 해결

---

android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MeetingDetailUiModelMapper.kt

fix: 로그화면 오디 버튼 사라지는 타이밍 변경

---

android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModel.kt
android/app/src/main/java/com/woowacourse/ody/presentation/room/log/model/MeetingDetailUiModel.kt

close #330 
<br>
<br>
<br>
추후에 로딩을 넣어야 합니다. 유저 입장에서 어색하긴 하네요.

fix: 로그 화면에서 값이 없는 화면이 나타나는 버그

---

android/app/src/main/res/layout/item_invite_code_log.xml

design: 초대 코드 item과 모임 정보 칸과의 간격을 늘림

---

android/app/src/main/res/layout/activity_notification_log.xml
android/app/src/main/res/layout/fragment_meeting_date.xml
android/app/src/main/res/layout/item_notification_log.xml

close #333 
<br>
<br>
[Screen_recording_20240810_133649.webm](https://github.com/user-attachments/assets/a6961642-d304-4b67-8223-8f4938065bfa)
<br>

fix: 로그 화면 닉네임들 길어지면 안보이는 버그 수정

---

backend/src/main/java/com/ody/common/annotation/FutureOrPresentDateTime.java
backend/src/main/java/com/ody/common/annotation/SupportRegion.java
backend/src/main/java/com/ody/common/validator/SupportRegionValidator.java
backend/src/main/java/com/ody/eta/dto/request/MateEtaRequest.java
backend/src/main/java/com/ody/mate/controller/MateController.java
backend/src/main/java/com/ody/mate/dto/request/MateSaveRequest.java
backend/src/main/java/com/ody/meeting/controller/MeetingController.java
backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequestV1.java
backend/src/test/java/com/ody/common/validator/SupportRegionValidatorTest.java

close #345 
<br>
- 수도권 외 지역 예외처리 커스텀 어노테이션 생성
- 약속 개설, 약속 참여, ETA 조회 request Dto에 검증 로직 적용
- 수도권 좌표 검증 로직: 아래 정사각형 좌표에 내 해당하는지 확인
<br>
Dto를 통해서 한번 검증이 이뤄지지만, 도메인에서도 중복으로 처리하는 게 좋을지 의견 궁금해요🤔

feat: 약속 참여자 ETA 조회 시, 수도권 외 지역 예외처리

---

backend/src/main/java/com/ody/meeting/domain/Meeting.java
backend/src/main/java/com/ody/notification/domain/FcmTopic.java
backend/src/main/java/com/ody/notification/dto/request/FcmSendRequest.java
backend/src/main/java/com/ody/notification/service/FcmPushSender.java
backend/src/main/java/com/ody/notification/service/FcmSubscriber.java
backend/src/main/java/com/ody/notification/service/NotificationService.java
backend/src/test/java/com/ody/notification/service/FcmEventSchedulerTest.java

close #366
<br>
아이디로 주제를 구독하는 방식을 유지하면서 <ins>약속 아이디를 uuid로 변경</ins>하는 것은 
- 초대코드 길이를 짧게 유지해야 한다는 조건을 만족할 수 없어 초대코드 생성 방안을 새로 마련해야 하므로 대안에서 제외했습니다
<br>
<ins>약속에 uuid 필드를 추가하고 이를 이용해 주제를 구독</ins>하는 것은
- 스키마 변경에 따라 감당해야 할 코드 수정이 지나치게 많아 대안에서 제외했습니다
<br>
<ins>약속 아이디, 약속 생성 시각을 인코딩</ins>해 inviteCode 필드에 저장하고, <ins>이를 초대코드, 주제 구독에 사용</ins>하는 것은
- 필드 추가의 부담이 없으나, 초대코드 길이를 짧게 유지해야 한다는 조건을 만족할 수 없어 대안에서 제외했습니다
- (참고) `1_2024-08-13T15:30:00.12345`이 `MV8yMDI0LTA4LTEzVDE1OjMwOjAwLjEyMzQ1Rd`로 인코딩됩니다
<br>
따라서 약속에 약속 생성 시각 필드를 추가하고 약속 아이디, 약속 생성 시각을 조합해 주제를 구독하는 방안을 택했습니다.
- 필드 추가가 있으나, `BaseEntity`를 사용함으로써 필드 추가에 따른 코드 수정이 발생하지 않습니다
- `{약속 아이디}_{약속 생성 시각}`을 주제로 사용하나, `:`은 주제에 포함될 수 없는 문자이므로 이를 `-`으로 대체했습니다
<br>
<br>

fix: 동일한 topic을 구독하여 참여하지 않은 메이트의 알림 받음

---

backend/src/main/java/com/ody/meeting/controller/MeetingController.java
backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
backend/src/main/java/com/ody/meeting/dto/response/MateEtaResponseV2.java
backend/src/main/java/com/ody/meeting/dto/response/MateEtaResponsesV2.java

close #400
<br>
- `ownerNickname` 대신 `requesterMateId` 제공
- `MateEtaResponse` 내 `mateId` 제공
- `ownerNickname`을 제공하지 않게 되면서 API가 깨져서 버전을 `v2`로 올렸습니다
<br>
<br>

docs: 약속 참여자 도착 현황 조회 API 문서화

---

backend/build.gradle
backend/src/main/java/com/ody/eta/domain/Eta.java
backend/src/main/java/com/ody/meeting/service/MeetingService.java
backend/src/main/resources/application.yml
backend/src/main/resources/schema.sql
backend/src/test/resources/application.yml

close #373
<br>
- MySQL DB를 실행할 EC2 생성 및 프로덕션 EC2 서버와 연결
- ddl 옵션을 validate로 변경
- schema.sql 추가
<br>
<br>

chore: MySQL DB를 실행할 EC2 생성 및 프로덕션 EC2 서버와 연결

---

backend/src/main/java/com/ody/common/interceptor/LoggingInterceptor.java
backend/src/main/java/com/ody/common/interceptor/ServletWappingFilter.java
backend/src/main/java/com/ody/common/interceptor/dto/RequestResponseWrappers.java
backend/src/main/resources/logback-spring.xml

close #355 
<br>
- File에 저장되는 로그에는 색상 옵션을 사용하지 않았습니다. -> File 내 불필요한 특수문자가 많이 들어가서 가독성 해침
- `LoggingInterceptor` 로그 출력 중복 코드 -> `RequestResponseWrappers` DTO로 분리
- `logback-spring.xml` 중복 코드 제거를 시도 -> 실패
시도한 방법들(공통 appender를 정의해서 extends 받는 방법, 여러 태그를 property로 한 번에 정의하는 방법, root 내에 공통 속성을 정의하는 방법.. 등)
-> **Q. 혹시 방법을 찾으셨다면 공유해주시면 감사드리겠습니다~!**
**[문제 상황]** request body 로그 출력시 의도치 않은 개행이 있었습니다.
**[원인]** Swagger에서 요청 body에 개행이 들어가기 때문이었습니다.
**[해결]** 개행, 공백2개 제거 `body.replaceAll("\\n|\\s{2}", "");`

chore: 로그 관련 중복 코드 제거 및 로그 내 Request Body 개행 제거

---

.github/workflows/android-cd-dev.yml

chore: 안드로이드 CD 구축

---

android/app/build.gradle.kts

close #484
<br>
<br>
https://github.com/user-attachments/assets/f88e0db1-e5cd-4c59-8c8e-7a8e4514b62b
<br>

fix: 카카오 웹 로그인 안되는 문제 수정

---

backend/src/main/java/com/ody/meeting/service/MeetingService.java
backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java

close #473 
<br>
<br>
<br>
- 약속 시간을 현재시간과 비교하여 지난 약속일 경우 400을 반환합니다.

refactor: 지난 약속에 참여하지 못하도록 예외처리

---

backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-local.yml
backend/src/main/resources/application-prod.yml
backend/src/main/resources/schema.sql

close #500 
<br>
> 스키마 수정
변경된 엔티티 구조와 스키마가 달라 Dev 서버의 컨테이너가 종료되었어요 
따라서 변경된 엔티티에 맞게 스키마 수정했습니다.
<br>
> 방언 설정 제거
방언 설정을 하고 있었는 데 아래 WARN 로그로 나오고 있었어요
```
MySQLDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
```
hibernate.dialect 속성을 명시적으로 설정할 필요가 없다고 나와있어
MySQL 드라이버를 사용하면 자동으로 MySQLDialect를 선택하여 해당 설정 제거했습니다.
<br>
<br>

chore: Dev 서버 Down 오류 해결 

---

.github/workflows/android-ci-dev.yml
android/app/build.gradle.kts
android/app/proguard-rules.pro
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/mulberry/ody/OdyApplication.kt
android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatastore.kt
android/app/src/main/java/com/mulberry/ody/data/remote/core/service/LogoutService.kt
android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoOAuthLoginService.kt
android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResult.kt
android/app/src/main/java/com/mulberry/ody/presentation/login/LoginActivity.kt
android/app/src/main/java/com/mulberry/ody/presentation/login/LoginNavigatedReason.kt
android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModelFactory.kt
android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModelFactory.kt
android/app/src/main/java/com/mulberry/ody/presentation/splash/SplashActivity.kt
android/app/src/main/res/layout/activity_splash.xml
android/app/src/main/res/values/strings.xml

close #498 
<br>
<br>
https://github.com/user-attachments/assets/d2f36226-77ab-43f7-9de3-c0c63530ba04
<br>
로그아웃 요청이 성공하던 실패하던 저장된 access token과 refresh token을 모두 접근할 수 없도록 삭제하는 방식으로 구현했습니다. 
(카카오도 동일하게 로그아웃에 실패하더라도 토큰을 삭제하는 방식으로 구현되어있네요. [카카오 로그아웃](https://developers.kakao.com/docs/latest/ko/kakaologin/android#logout))
지금은 로그아웃 요청이 실패했을 때 토큰을 지워버리니 로그아웃 재요청을 하지 못하고 서버에 만료 기간이 남은 refresh token이 그대로 남아버리는데요, [logout만을 위한 token을 발급하는 방법](https://medium.com/android-news/solving-offline-logout-problem-f3b50da49e7e)이 있는 것 같습니다. access token을 지우지 않고 계속 재시도하는 방법이 있으나, 앞선 링크에 "저장된 토큰을 누군가 탈취할 수도 있다" 소개되어 있네요. 좋은 예시는 아니나 토큰을 남기는게 별로 좋지 않다는건 동의하고 있습니다.
이대로도 동작에는 문제가 없고, refresh token도 만료 기간이 지나면 쓸 수 없게되니 지금은 그냥 둬도 괜찮지 않을까? 하는 생각입니다. 다른 할 일들도 있고.. 이후에 토큰을 저장할 때 암호화해서 저장하는 것도 생각해 볼 일인 것 같아요.(지금 말고)

feat: 로그아웃 기능 구현

---

android/app/src/main/res/layout/activity_meeting_join.xml
android/app/src/main/res/layout/fragment_meeting_destination.xml

design: 기본적으로 보여주던 수도권 안내 멘트 삭제

---

backend/src/main/java/com/ody/notification/domain/Notification.java
backend/src/main/java/com/ody/notification/domain/NotificationType.java
backend/src/main/java/com/ody/notification/service/FcmPushSender.java
backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java

close #508 
<br>
- 출발 알림이 아닌 type들의 초기 상태를 DONE으로 변경
- 출발 알림만 DONE 상태로 변경하는 Update 쿼리를 실행하고 상태 변경 로그가 찍히도록 수정
<br>
<br>

refactor: 출발 알림이 아닌 type들의 초기 상태를 DONE으로 변경

---

backend/src/main/java/com/ody/common/domain/BaseEntity.java
backend/src/main/java/com/ody/meeting/controller/MeetingController.java
backend/src/main/java/com/ody/meeting/domain/Meeting.java
backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
backend/src/main/java/com/ody/meeting/service/MeetingService.java
backend/src/main/java/com/ody/util/InviteCodeGenerator.java
backend/src/main/resources/application-dev.yml
backend/src/main/resources/schema.sql
backend/src/test/java/com/ody/common/Fixture.java
backend/src/test/java/com/ody/mate/service/MateServiceTest.java
backend/src/test/java/com/ody/meeting/repository/MeetingRepositoryTest.java
backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
backend/src/test/java/com/ody/util/InviteCodeGeneratorTest.java

close #506 
<br>
> 인코딩 방식 제거
기존에 ID로 초대코드를 인코딩하던 방식이 meeting 저장 시 기본 초대코드 저장 -> 반환된 meeting의 ID로 초대코드 인코딩해 update하는
좋지 않은 흐름들을 만든다고 생각했어요
ID를 사용하나 텍스트를 사용해 조회하던 알아본 결과 텍스트가 너무 길거나 Like 문의 %을 문자열 앞에 붙이는 등이 있지만 않다면
큰 성능 차이가 없는 것 같았습니다.
따라서 기존의 인코딩 방식을 제거하고 다음과 같은 방법으로 유일성이 높은 8자리의 초대 코드를 생성하도록 했어요.
```
UUID의 앞 글자를 따 SHA-256으로 해쉬화된 Byte 추출
추출된 Byte의 앞 4글자를 16진수로 변환해 2글자씩 추가 -> 4  * 2 = 8 글자 추출
```
<br>
> 초대코드 타입 및 제약조건 추가
8글자 고정으로 생성되기에 type을 가변인 varchar() -> char(8)로 변경했습니다.
고정형 타입을 사용함으로써 데이터가 항상 일정한 크기를 가져 데이터를 저장하고 검색하는 데에 효율적이라고 하더라구요
유일성이 높아졌고 중복될 수 없기에 unique 제약조건을 추가했습니다
이로인해 논 클러스터링 인덱스가 생성되 조회시에 더 빠르게 조회가 가능할 것 같아요
<br>
<br>

refactor: 초대코대 코드 유일성 높이도록 개선

---

.github/workflows/backend-cd-dev.yml
backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
backend/src/main/resources/common.yml

close #544 
<br>
무료로 발급 받은 DNS가 예정된 만료일 보다 빨리 만료되어 서버 접속이 불가했음.
=> 가비아에서 새로 발급한 oody.site 도메인으로 재등록하여 해결
추가로 애플리케이션 재실행마다 스케줄링 작업이 실행될 때 
findAllByTypeAndStatus()로 가져온 Notification 엔티티 내부의 엔티티들의 값에 접근할 때 
Lazy 예외가 발생하는 것이 문제였음.
=> findAllByTypeAndStatus()에 Fetch Join을 추가해 해결
<br>
<br>

fix: Dev 서버 Swagger 접속 에러 해결 

---

backend/src/main/java/com/ody/mate/service/MateService.java

close #571 
<br>
-[x] odsay가 계속 호출되는 문제 해결
- 문제 원인 : outer method에 @transactional이 붙여져 있지 않아서 update가 안됨
<br>
<br>

fix: odsay 호출 문제 해결

---

backend/src/main/java/com/ody/common/validator/SupportRegionValidator.java
backend/src/test/java/com/ody/common/validator/SupportRegionValidatorTest.java

close #601 
<br>
- 문제 원인 : 행방 불명 상태에서 request에 담아주는 0.0 좌표가 수도권 검증 로직에서 404반환
- 해결 방법 : 수도권 검증 로직에서 missingCoordinate인 0.0을 허용하도록 변경
<br>
<br>

fix: 수도권 검증 로직에서 missing 좌표도 추가

---

backend/src/main/java/com/ody/meeting/service/MeetingService.java
backend/src/main/java/com/ody/notification/domain/Notification.java
backend/src/main/java/com/ody/notification/service/FcmPushSender.java
backend/src/main/java/com/ody/notification/service/NotificationService.java

close #597 
<br>
- 입장 알림은 fcmTopic이 null이여서 문제가 발생했었음, 입장 알림 생성시 fcmTopic 추가
- ETA 공지 알림은 정확히 무슨 이유인지 확인하기 위해 로깅 추가
<br>
<br>

hotfix: 입장, ETA 공지 알림 오지 않는 문제 해결

---

backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
backend/src/main/java/com/ody/notification/service/NotificationService.java
backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java

close #606 
<br>
- 로그들을 가져오는 쿼리에서 now()가 UTC 기준으로 찍히는 문제 > 조회 기준점을 파라미터로 받게 수정
<br>
<br>

hotfix: 약속방 로그가 뜨지 않는 문제 해결

---

backend/src/main/java/com/ody/notification/domain/FcmTopic.java

close #609
<br>
save() 시에 반환된 meeting 객체에서 createAt()을 가져올 경우 가공된 형식이 아닌 LocalDateTime의 기본 형식이 반환되는 문제로
같은 meeting으로 생성된 FcmTopic이라도 Mate 참여시에 생성된 FCM 토픽과 모임 생성시 생성된 FCM 토픽이 달라 알림이 가지 않았음.
`DateTimeFormatter`로 createAt() 형태를 고정해놓았음.
<br>
<br>

fix: ETA 공지 알림 오지 않는 문제 해결

---

backend/build.gradle
backend/src/main/java/com/ody/notification/service/NotificationService.java

close #614 
<br>
OSIV false 설정으로 인해 해당 메서드까지 영속성 컨텍스트가 살아있지 못해서 Lazy 예외가 발생
=> 트랜잭션 선언으로 영속성 컨텍스트 생명 범위 확장
<br>
<br>

hotfix: OSIV false 설정으로 인한 스케줄링 메서드 트랜잭션 선언

---

backend/src/main/java/com/ody/common/config/ReplicationDataSourceRouter.java

close #620
<br>
로그가 항상 `(트랜잭션 활성화 여부 : true) (readOnly : true)`로 떠서 확인해보니 변수가 제대로 안 들어가고 있었음
<br>
<br>

bugfix: READ, WRITE DB 선택 로그

---

.github/workflows/android-cd-dev.yml

chore: 안드로이드 cd 배포 위치 테스트 트랙에서 프로덕션 트랙으로 변경

---

backend/src/main/java/com/ody/mate/service/MateService.java
backend/src/main/java/com/ody/meeting/controller/MeetingController.java
backend/src/main/java/com/ody/meeting/service/MeetingService.java
backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java

close #643 
<br>
- 기존에는 모임 기참여자라도 초대코드가 유효하다면 200을 반환 > api 문서 스펙에 따라 참여했다면 400반환하도록 수정
<br>
<br>

refactor: 초대코드 검증 시 참여여부 확인하도록 수정

---

backend/docker-compose.yml

close #673
<br>
dev 서버에서만 docker 내 로그 파일에는 로그가 생기는데 EC2 내 로그 파일에는 업데이트가 안 되어서 
prod와 dev의 volume 설정 비교해봤습니다
```
docker inspect ody-***-app | grep -A 5 "Mounts"
```
```
"Mounts": [
{
"Type": "bind",
"Source": "/var/logs/ody-prod-logs",
"Destination": "/ody-prod-logs",
"Mode": "",
```
```
"Mounts": [
{
"Type": "volume",
"Source": "ubuntu_ody-dev-logs-vol",
"Target": "/ody-dev-logs",
"VolumeOptions": {}
--
"Mounts": [
{
"Type": "volume",
"Name": "ubuntu_ody-dev-logs-vol",
"Source": "/var/lib/docker/volumes/ubuntu_ody-dev-logs-vol/_data",
"Destination": "/ody-dev-logs",
```
<br>
Source를 확인해보면 지정하고자 한 경로가 아니라 EC2 내 로그 파일 업데이트가 안 되는 상황인 것 같아요
그래서 docker-compose.yml에서 수정을 해주었습니다~!
<br>
추가로, Type이 다른 게 궁금해서 찾아봤는데 volume과 bind mount가 다른 개념이네요!
volume은 docker가 관리하는 거고 일반적으로 /var/lib/docker/volumes/ …

chore: dev 로그 미수집 원인 해결

---

backend/src/main/java/com/ody/common/exception/GlobalExceptionHandler.java

close #686
<br>
NoResourceFoundException 에러 로그가 slack 알림으로 계속 와서 중요한 에러 로그가 잘 안 보여서 에러 핸들링 했습니다
<br>
<br>

feat: NoResourceFoundException error handling

---

android/app/src/main/AndroidManifest.xml

close #678 
<br>
<br>
<br>
원래 출발지 입력 화면에서 주소 입력 Fragment 진입해서도 다음 버튼이 계속 남아있는 버그가 있었는데요!!
(play store에 올라간 앱 버전도 이 현상 존재함..)
현재 develop pull 받아서 다시 설치하니까 제 의도대로 다음 버튼이 없어졌더라구요 ㄷㄷ 나는 해결한 기억이 없는데.... 황당tv
그런데 키보드 올라올 때 주소 입력 Fragment의 사이즈도 변경되면 더 자연스러울 것 같아서, 그 속성만 추가해서 pr 올립니다!!

design: 주소 입력 화면의 windowSoftInputMode 속성 추가

---

.github/workflows/android-cd-dev.yml

chore: android cd 트리거 브랜치 네임으로 변경

---

.github/workflows/backend-cd-prod.yml
backend/src/main/resources/application-prod.yml
backend/src/main/resources/common.yml

close #646 
<br>
- Rolling : 실행중인 서버들을 점진적으로 신버전으로 교체
[출처](https://ksh-coding.tistory.com/119)
1. 문제 발생 시 롤백이 간편하다.
2. 별도의 추가 EC2 자원이 필요하지 않다.
3. 서버가 2대에서 변동 가능성이 거의 없다.
4. blue green 전략을 고려했으나, AWS 오토 스케일링 권한이 없어 도입할 수 없고, Nginx도 고려했으나 네트워크 통신 단계가 많아 비효율적으로 판단했다.
- 서비스에 신버전, 구버전이 공존하기 때문에 균일한 서비스를 제공하지 못한다는 단점이 있지만, 2개의 자원만 가동하므로 큰 문제가 되지 않는다고 판단했음.
- cd 파이프라인에서 ec2 직렬로 이미지 run 후, 기존 구현되어 있던 `actuator/health` api 사용하여 헬스체크
- 헬스체크에 실패하면 다음 작업으로 넘어가도록 우선 구현해 둠 -> 롤백 구현하면서 개선해야 하는 포인트
<br>
<br>

chore: 무중단 배포 적용

---

android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingFragment.kt

refactor: BindingFragment에서 analytics 가능하게 수정

---

android/app/build.gradle.kts
android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchFragment.kt
android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchViewModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationActivity.kt
android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/creation/date/MeetingDateFragment.kt
android/app/src/main/java/com/mulberry/ody/presentation/creation/destination/MeetingDestinationFragment.kt
android/app/src/main/java/com/mulberry/ody/presentation/creation/time/MeetingTimeFragment.kt
android/app/src/main/java/com/mulberry/ody/presentation/login/LoginActivity.kt
android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
android/app/src/test/java/com/mulberry/ody/presentation/address/AddressSearchViewModelTest.kt
android/app/src/test/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModelTest.kt
android/gradle/libs.versions.toml

close #640 
<br>
<br>
<br>
- MutableLiveData -> MutableStateFlow
- LiveData -> StateFlow
- MediatorLivedata -> combine
- MutableSingleLiveData -> MutableSharedFlow
- SingleLiveData -> SharedFlow
Flow로 다 마이그레이션 하면 MutableSingleLiveData 지워야 합니다!

refactor: ViewModel의 LiveData를 Flow로 변경

---

android/app/src/main/AndroidManifest.xml

close #722
<br>
<br>
<br>
정확한 알림을 받기 위한 permission 종류가 두가지가 있는데요.
`SCHEDULE_EXACT_ALARM`랑 `USE_EXACT_ALARM`입니다.
저는 `SCHEDULE_EXACT_ALARM`를 사용하고 있었는데, 이 경우 사용자에게 명시적으로 권한을 받아야 한다고 하더라구요.
그런데 권한을 받는 코드가 없어서 생기는 오류였어요.. (왜 내 폰은 잘 되지..)
`USE_EXACT_ALARM`는 명시적으로 권한을 받지 않아도 되어서 편리하지만, 그만큼 더 구글의 제약사항들이 많은 것 같아요.
그래서 `USE_EXACT_ALARM`는 앱의 핵심기능이 정확한 알람인 경우에만 사용하라고 권장하고 있는데, 저희는 핵심기능이 정확한 알람이니 일단 `USE_EXACT_ALARM`로 변경해보겠습니다..!! 
PR merge되면 바로 앱 업데이트 올릴게요
참고 공식 문서: https://developer.android.com/develop/background-work/services/alarms/schedule?hl=ko#exact-permission-declare

hotfix: 스케줄링 정확한 알림 권한 수정

---

android/app/src/main/res/layout-sw1080dp/fragment_meeting_date.xml
android/app/src/main/res/layout-sw1080dp/fragment_meeting_time.xml
android/app/src/main/res/layout-sw720dp/fragment_meeting_date.xml
android/app/src/main/res/layout-sw720dp/fragment_meeting_time.xml

close #704 
<br>
<br>
9인치 TimePicker, DatePicker
12인치 TimePicker, DatePicker
<br>
이후에 글씨 크기를 조금 키우는 것이 좋을 것 같습니다.
실 기기로 느낌을 좀 볼 수 있으면 좋을텐데..

design: 9인치, 12인치 화면에서 DatePicker, TimePicker 크기 수정

---

android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchFragment.kt
android/app/src/main/java/com/mulberry/ody/presentation/common/DimensionExtensions.kt
android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt

close #742
<br>
<br>
<br>
divider 컬러가 피그마랑 조금 다르길래 명시적으로 지정해주었습니다!
dp to px 함수가 이미 구현되어있길래, common 확장함수로 분리했어요

design: 주소 검색 item 디자인 수정

---

android/app/src/main/java/com/mulberry/ody/presentation/login/LoginActivity.kt

close #745 
<br>
<br>
https://github.com/user-attachments/assets/44525fb4-288d-400a-a3ed-746d97fa055b
<br>

fix: 로그인 후 뒤로가기를 하면 앱이 종료되지 않고 로그인 화면으로 돌아가는 문제 수정

---

backend/src/main/java/com/ody/meeting/service/MeetingService.java
backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java

close #700 
<br>
새벽 4시마다 실행되는 scheduleOverdueMeetings() 메서드도 이전 스케줄링 문제와 동일하게
OSIV false로 Lazy 문제가 발생해 트랜잭션 범위에 넣어주어 해결했습니다.
추가로 4시마다 스케줄링된다는 부분을 테스트 추가했는데
현재는 실제 실행되는 상황과 동일하게 맞춰 테스트를 하지만
실제 스케줄링된 작업에 대한 테스트를 보장하진 않기 때문에 정책이 4시가 아닌 다른 시간으로 변경되면 테스트가 애매하긴해요
하지만 실제 스케줄링된 작업을 테스트하기 위해선 특정 시간만큼 기다리는 방법밖에 없는 것 같아 이 방법으로 추가해봤습니다
<br>
<br>

fix: 새벽 4시에 약속 삭제 로직 Lazy 에러 해결

---

android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardCloseBroadcastReceiver.kt
android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardService.kt

close #747 
<br>
<br>
<br>
`Service` 객체가 싱글톤 인스턴스이기 때문에, `stopService()`를 호출하면 서비스 객체가 소멸되어 모든 폴링 작업이 끝나는 현상이 있었습니다. 즉, 동시에 여러 약속에 대한 폴링 작업을 수행 중인 경우 하나의 폴링 작업이 끝나면 모든 폴링 작업이 끝난다는 버그가 존재했습니다.
이를 아래 방식으로 해결했습니다~
1. 폴링 작업을 끝내야 할 때 `stopService()`를 호출하지 않고, `startForegroundService()`를 호출
2. Serivce 내부에서 폴링 작업이 0개인 경우에만 `stopSelf()`를 통해 서비스 인스턴스를 소멸시키도록 수정

fix: Foreground Service 여러 작업 수행 가능하도록 수정

---

android/app/src/main/res/layout/item_meeting_catalog.xml
android/app/src/main/res/layout/toolbar_notification_log.xml

close #759
<br>
<br>
<br>
https://github.com/user-attachments/assets/e4810da2-c28d-4a87-b402-af0a4ad57a88

design: 약속 이름이 길 때 말줄임표 대신 약속 이름을 최대한 보여줄 수 있도록 수정

---

android/app/src/main/res/layout/activity_meeting_creation.xml

close #754 
<br>
<br>
https://github.com/user-attachments/assets/5c39ae75-d1ca-422f-8021-4438f0d1c520
가끔 보이는 조그만한 하얀 원같은게 터치 지점입니다
<br>

fix: 원(인디케이터)을 통해 강제 이동 가능 막기

---

android/app/src/main/res/layout/fragment_notification_log.xml

fix: 다크모드 초대코드 복사 창에서 왼쪽 위 흰색 제거

---

android/app/src/main/res/values-night/themes.xml

close #805 
<br>
<br>
- Before
<br>
- After <br>
<br>

fix: 다크모드일 때 스플래시 로고 이상하게 보이는 문제 수정

---

backend/src/main/java/com/ody/mate/service/MateService.java
backend/src/test/java/com/ody/mate/service/MateServiceTest.java

close #795 
<br>
<br>
<br>
- nudge에 대한 검증조건을 추가하면서 느낀 건데 nudge에 대한 조건이 조금 커지면서 이제 분리할 시기가 온 것 같아요. 현재는 모든 nudge 관련 도메인이 mateService 내에 녹아있는데 어떻게 분리하면 좋을지 의견 받습니다. 저는 개인적으로 etaService 안으로 넣어주거나, nudgeService를 새로 만드는 것도 방법이라 생각합니다. 다만 이 경우 mateSevice가 nudgeService를 가지게 되므로 의존성이 과해진다는 문제가 생길 수도 있을 것 같아요.

refactor: 약속 시간 이후 30분까지 nudge가 가능하도록 수정

---

android/app/src/main/java/com/mulberry/ody/data/local/db/OdyDatabase.kt
android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/MateEtaListTypeConverter.kt
android/app/src/main/java/com/mulberry/ody/data/local/entity/eta/OldMateEtaListTypeConverter.kt
android/app/src/main/java/com/mulberry/ody/domain/model/EtaType2.kt
android/app/src/main/java/com/mulberry/ody/domain/model/MateEta2.kt

close #831
<br>
<br>
<br>
Room에 저장된 EtaType이 사라지고 EtaStatus로 대체되었는데요.
이 과정에서 기존 EtaType으로 저장된 Entity들이 제대로 변환되지 않아 계속 앱이 터졌었어요.
EtaType -> EtaStatus 마이그레이션 코드 작성했습니다! 
그런데 코드가 너무 더러워요................ 일단.... 이대로 머지하고 앱 업데이트 이후 리팩터링해도 될까요?
EtaStatus 리팩터링 쉬운 줄 알았는데 고려할게 많네요 흑흑흑흑흑흑흑흑

fix: Room Entity 마이그레이션 버그 수정

---

README.md
android/README.md
backend/README.md

close #836 
<br>
백엔드 리드미 추가
[여기서 보면 편하게 보실 수 있습니다.](https://github.com/woowacourse-teams/2024-ody/blob/5e2eb4b756abd48cccc803160546b22539893b36/backend/README.md)
<br>
<br>
패키지 구조가 너무 긴데 디렉토리 뎁스를 낮추는게 나을까요 ??

docs: 백엔드 리드미 추가

---

.github/workflows/android-cd-dev.yml

close #847
<br>
<br>
<br>
공개테스트 1001 버전으로 테스트했고, 로그인 잘 되는 것 같습니다.

fix: cd 스크립트 local.properties 제대로 들어가지 않는 문제 수정

---

android/app/src/main/res/values/strings.xml

close #751
<br>
<br>
<br>
푸시 알림 문자열과 로그 화면 문자열에 있는 `~이가`를 `~님이`로 변경했습니다.
그런데 닉네임 뒤에 `님`을 붙이면서, `친구`라는 단어도 안 쓰는 쪽으로 수정해야 조금 더 자연스러울 것 같아요.
`친구` 단어를 사용한 문자열들은 아래와 같습니다.
```
- %s 약속에 참여한 친구 위치를 확인해 보세요!
- 초대 코드를 복사해 친구에게 전달해 보세요!
- 위치 권한을 거절하면 내 위치를 친구에게 공유할 수 없어요
- 친구의 위치 권한이 꺼져있어요.
- 친구들의 도착 예정 정보를 확인해보세요!
- 친구와 도착 정보를 공유하고 있어요.
- 지각 위기 버튼을 눌러 친구를 재촉해 보세요.
- 약속 시간 30분 전부터 친구들의 위치 현황을 확인해 보세요.
- 지각 버튼을 눌러 친구를 재촉해 보세요.
- 약속 시간 이후부터는 친구들의 지각 여부를 확인할 수 있어요.
```
이 `친구`를 어떤 단어로 대체할지 아직 잘 모르겠어요.. 어떤 걸 대입해도 조금 어색해요.
그래서 emergency 채널에 `<~님 + 친구를 다른 단어로 대체하기>` or `<변경하지 말기(~이가 + 친구 그대로)>` 이 두 가지를 투표 받으려고 합니다.
일단 수정한 부분 PR은 올려두겠습니다!

design: 로그 화면의 문자열 수정

---

.github/workflows/android-cd-dev.yml

fix: 안드로이드 cd 배포 시 개인정보 페이지 열리지 않는 문제 수정

---

android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/join/listener/MeetingJoinListener.kt
android/app/src/test/java/com/mulberry/ody/presentation/join/MeetingJoinViewModelTest.kt

close #851 
<br>
<br>
<br>
replay가 없어서 Flow가 최근에 발행한 값을 다시 새로운 구독자에게 제공할 수 있도록 설정했습니다. UI 컴포넌트가 다시 구독할 때 이전 상태를 잃지 않고 최신 상태를 유지할 수 있게 했습니다.
conflate는 필요성을 못느껴서 삭제했습니다!. 그리고 onClick에서 두 메서드를 부르는게 어색하고 디버깅이 어려워서 클릭메서드 호출로 변경했습니다.
이상한 점 있으면 말씀해주세요!

fix: 약속 참여할 때 가끔 바로 로그화면으로 가지지 않는 버그 수정

---

android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultMatesEtaRepository.kt

close #881
<br>
<br>
https://github.com/user-attachments/assets/f4fb9a0a-184f-4852-8a37-5e59c5be9fe3
약속 나간 경우 foreground service 알림이 없어지는지 확인하는 영상입니다
<br>
reservation 엔티티는 삭제하는 코드는 작성했었는데
service stop하는 코드를 놓쳤네요..!!!

fix: 약속을 나간 경우에도 eta 폴링 요청을 계속 보내는 버그 수정

---

backend/src/main/java/com/ody/mate/service/MateService.java

close #908
<br>
유저에게 그대로 노출되는 에러 메세지라서 해음의 요청에 따라 자연스러운 메세지로 수정합니다
해당 PR이 머지되면 버전 2.3.2로 배포하겠습니다~
<br>
<br>

refactor: 약속방 중복참여 에러 메세지 수정

---

android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/ErrorResponse.kt
android/app/src/main/java/com/mulberry/ody/data/retrofit/ApiResultCall.kt
android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResult.kt
android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResultExtensions.kt
android/app/src/main/java/com/mulberry/ody/presentation/common/binding/BindingActivity.kt
android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeActivity.kt
android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModel.kt
android/app/src/test/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModelTest.kt

close #893 
<br>
<br>
1. 이상한 코드 입력 시
2. 이미 참여한 방 참여 시
3. 과거 약속 참여 시
옛날 초대 코드 입력하고 싶은데 있으신 분..
<br>

refactor: 초대코드 유효하지 않은 메시지 서버로부터 받게 변경

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultMatesEtaRepository.kt
android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardCloseBroadcastReceiver.kt
android/app/src/main/java/com/mulberry/ody/data/local/service/ReinstallBroadcastReceiver.kt

close #899 
<br>
<br>
<br>
안드로이드는 앱 업데이트 하면 AlarmManager의 스케줄링들이 모두 삭제된다고 해요.
앱 업데이트를 트리거할 수 있는 BroadcastReceiver를 등록하고, 이 BroadcastReceiver에서 Room에 저장된 스케줄링들을 다시 AlarmManager에 등록하는 코드 구현했습니다!
개발하면서 재부팅 시에도 AlarmManager 스케줄링 재등록하도록 추가했어요
이 글을 참고했습니다. -> https://stackoverflow.com/questions/49704914/alarmmanager-when-app-is-updated

fix: 앱 업데이트 및 재부팅 시 alarm 등록하는 BroadcastReceiver 추가

---

backend/src/main/java/com/ody/common/config/RedisConfig.java
backend/src/main/resources/common.yml

close #917 
<br>
미션에서 설정할 때는 LettuceConnectionFactory를 파라미터 없이 생성하면
기본적으로 프로퍼티의 설정을 읽어 세팅되어 몰랐는데
redisStandaloneConfiguration은 host와 port를 설정해주지않으면 기본적으로 localhost로 등록이 되버리네요..
따라서 호스트와 포트를 지정해주었습니다
```
@Bean
public RedisConnectionFactory redisConnectionFactory() {
RedisStandaloneConfiguration configuration = new RedisStandaloneConfiguration();
configuration.setHostName(host);
configuration.setPort(port);
return new LettuceConnectionFactory(configuration);
}
```
<br>
<br>

chore: Redis 연결 설정 오류 해결

---

android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomViewModel.kt

close #853 
<br>
<br>
<br>
잘되는거 확인했습니다! 
동일한 에뮬레이터에서 앱을 실행한뒤 방 생성(오디냥 계정으로) -> 어플 삭제 -> 어플재설치 -> 방 참여(해음 계정으로)
왜 인지는 모르겠지만 실기기와 에뮬레이터로 하니 잘 되네요!

fix: 재촉을 못할때는 재촉 요청이 안가게 수정

---

android/app/build.gradle.kts
android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/AddressPagingSource.kt
android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/KakaoAddressRepository.kt
android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/KakaoAddressService.kt
android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/response/AddressResponseMapper.kt
android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResultExtensions.kt
android/app/src/main/java/com/mulberry/ody/domain/model/Addresses.kt
android/app/src/main/java/com/mulberry/ody/domain/repository/location/AddressRepository.kt
android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchFragment.kt
android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchViewModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/address/adapter/AddressesAdapter.kt
android/app/src/main/java/com/mulberry/ody/presentation/address/listener/AddressListener.kt
android/app/src/main/java/com/mulberry/ody/presentation/address/listener/AddressViewHolder.kt
android/app/src/main/java/com/mulberry/ody/presentation/address/model/AddressUiModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/address/model/AddressUiModelMapper.kt
android/app/src/main/res/layout/item_address_search.xml
android/app/src/test/java/com/mulberry/ody/TestFixtures.kt
android/app/src/test/java/com/mulberry/ody/fake/FakeAddressRepository.kt
android/app/src/test/java/com/mulberry/ody/presentation/address/AddressSearchViewModelTest.kt
android/gradle/libs.versions.toml

close #677
<br>
<br>
https://github.com/user-attachments/assets/46082fbd-ad12-415d-8f14-78bfe1ec8de5
영상에는 한번에 로드하는 것 같아보이지만 ㅎㅎ 로그 찍어보니 지연 로딩 잘 되었습니다
<br>
학습 + 구현 부담 감소를 위해 paging3 라이브러리를 사용해봤어요 
언제 다음 페이지를 로드할지를 신경쓰지 않아도 되니 편하네요!
무한 스크롤을 위해 핵심이 되는 코드는 `AddressPagingSource`입니다
paging3 내부적으로 다음 페이지를 로드할 시점이 되면 `AddressPagingSource`의 `load()` 함수를 호출한다고 합니다
구체적인 라이브러리 사용 방법은 구글에 서치만 해도 많이 나와있어서, 전체적인 흐름을 요약해보았어요~
```
1. data단의 AddressPagingSource에서 페이지 load
2. ViewModel에서 로드한 페이지를 emit
3. Fragment에서 emit한 페이지 데이터 collect
4. PagingDataAdapter(ListAdapter와 유사한 친구)에서 ui 노출
```
paging3 라이브러리를 잘 모른다면 이해하기 어려울 수도 있을 것 같은데 코드 리뷰하면서 마음껏 질문해주셔도 좋습니다~!!!

feat: 주소 검색 무한 스크롤 구현

---

backend/src/main/java/com/ody/auth/token/AccessToken.java
backend/src/main/java/com/ody/auth/token/RefreshToken.java
backend/src/test/java/com/ody/auth/token/AccessTokenTest.java
backend/src/test/java/com/ody/auth/token/RefreshTokenTest.java

close #622
<br>
헤더가 널일 때 NPE가 발생해 500이 반환되어 안드 측에서 에러 확인 문의가 반복적으로 일어나 해결합니다 
<br>
<br>

fix: 헤더가 빈 값이면 NPE 발생

---

.github/workflows/backend-cd-dev.yml
backend/src/main/resources/application-dev.yml
backend/src/main/resources/application-prod.yml

close #927
<br>
개발 서버 마이그레이션 과정 중에 레디스 호스트 변경으로 yml 파일 수정이 있었습니다
<br>
<br>

chore: 개발 서버 마이그레이션

---

android/app/src/main/java/com/mulberry/ody/data/auth/repository/KakaoAuthRepository.kt
android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardService.kt
android/app/src/main/java/com/mulberry/ody/data/retrofit/AccessTokenInterceptor.kt
android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResultExtensions.kt
android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/login/LoginViewModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomViewModel.kt
android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt

close #948 
<br>
<br>
<br>
`suspendOnXXX()`랑 `onXXX()` 함수가 두개씩 있는게 유지보수성과 가독성이 좋지 않은 것 같아서
코틀린의 `Result`의 `onXXX()`는 어떻게 구현되어있는지 찾아봤어요.
그런데 `suspend` 처리에 관련된 로직은 안보이고 그냥 `inline` 키워드가 붙어있더라구요 ..
람다가 호출한 쪽에 `inline`되는 거면 호출한 쪽의 컨텍스트에 따라 `suspend` 함수를 호출할 수 있으니 `suspendOnXXX()`를 굳이 만들 필요가 없었어요!
추가적으로 `ApiResultExtensions`에서 `suspend` 붙은 함수들 모두 적용했습니다.
호출하는 쪽에서 `suspend`인지 아닌지에 따라 호출할 함수를 결정하는 건 좋지 못한 방식인 것 같아서요 ...
넘 간단하게 해결해서 기분 좋음 ㅎ

refactor: suspendOnXXX() 함수 제거

---

android/app/src/main/java/com/mulberry/ody/presentation/common/LocalDateTimeMapper.kt
android/app/src/main/java/com/mulberry/ody/presentation/meetings/model/MeetingUiModelMapper.kt
android/app/src/main/res/layout/item_meeting_catalog.xml
android/app/src/main/res/values/strings.xml

close #971
<br>
<br>
<br>
도착지까지 걸리는 시간이 70분인 경우, 
메인화면에서는 "70분 걸려요"라고 뜨고 상세 화면에는 "1시 10분 걸려요"라고 뜨는 오타가 있어서 수정했습니다 ㅜ!!!! 바보같은 실수를...

design: 도착지까지 걸리는 시간 문구 수정

---

backend/src/main/resources/common.yml

close #983
<br>
2025-03-23 일자로 사용기간이 만료되어 새로운 API Key로 교체합니다!
<br>
<br>

chore: 사용기간 만료에 따른 ODsay API Key 교체

---

backend/src/main/java/com/ody/mate/service/MateService.java
backend/src/main/java/com/ody/meeting/controller/MeetingController.java
backend/src/main/java/com/ody/meetinglog/domain/MeetingLog.java
backend/src/main/java/com/ody/meetinglog/domain/MeetingLogType.java
backend/src/main/java/com/ody/meetinglog/repository/MeetingLogRepository.java
backend/src/main/java/com/ody/meetinglog/service/MeetingLogService.java
backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponses.java
backend/src/main/java/com/ody/notification/service/FcmPushSender.java
backend/src/main/java/com/ody/notification/service/NotificationService.java
backend/src/main/java/com/ody/util/ScheduleRunner.java
backend/src/main/resources/db/migration/V13__add_meeting_log_table.sql
backend/src/test/java/com/ody/common/BaseRepositoryTest.java
backend/src/test/java/com/ody/common/FixtureGenerator.java
backend/src/test/java/com/ody/common/FixtureGeneratorConfig.java
backend/src/test/java/com/ody/eta/service/EtaSchedulingServiceTest.java
backend/src/test/java/com/ody/mate/service/MateServiceTest.java
backend/src/test/java/com/ody/meetinglog/repository/MeetingLogRepositoryTest.java
backend/src/test/java/com/ody/notification/service/FcmPushSenderTest.java
backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java

close #981 
<br>
- 도메인 분리 5단계 중 1단계인 MeetingLog 도메인을 추가합니다.
**- 1단계 : MeetingLog 도메인을 추가한다.**
2단계 : ETA_SCHEDULING_NOTICE 를 trigger 도메인으로 분리한다.
3단계 : Notification과 ReservedNotification 도메인으로 분리한다.
4단계 : Dev와 Prod 환경의 data를 마이그레이션한다.
5단계 : 3-4단계 리팩터링 내역을 merge 한다
<br>
<br>
- 개인적으로 notificationService에서 send 이후에 update를 하면 fcmPushSender에 있는 update 로직을 제거할 수 있어서 그렇게 하고 싶은데, 비동기로 이벤트 수신 후, 에러가 발생하는 경우에 대응하지 못해요. 제리는 어떻게 생각하나요?

refactor: meetingLog 도메인 추가

---

backend/src/main/java/com/ody/auth/dto/response/AppleAuthValidationResponse.java
backend/src/test/java/com/ody/auth/dto/response/AppleAuthValidationResponseTest.java

close #994
<br>
발생한 에러:
```
jakarta.validation.ConstraintViolationException: Validation failed for classes [com.ody.auth.domain.MemberAppleToken] during persist time for groups [jakarta.validation.groups.Default, ]
List of constraint violations:[
ConstraintViolationImpl{interpolatedMessage='널이어서는 안됩니다', propertyPath=appleRefreshToken, rootBeanClass=class com.ody.auth.domain.MemberAppleToken, messageTemplate='{jakarta.validation.constraints.NotNull.message}'}
```
원인:
Apple에서 제공하는 JSON 형식과 맞지 않아 refreshToken 필드에 널 값이 들어감
이후 MemberAppleToken을 저장하려는 과정에서 appleRefreshToken의 NotNull 조건에 부합하지 않아 에러 발생함
<br>
<br>

fix: 애플 로그인 AppleRefreshToken 널 값 에러 해결

---

android/app/build.gradle.kts
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardService.kt

close #1028
<br>
<br>
<br>
fcm 우선순위 변경한 거 관련해서 수정사항 있으면 적용하려했는데 안드로이드 쪽에서 수정할만한 건 없었어요!!
[foreground service type](https://developer.android.com/about/versions/14/changes/fgs-types-required?hl=ko#location) 쪽 수정할게 있어서 그 부분 수정하면서 sdk 버전도 올렸습니다

refactor: sdk 버전 변경 및 포그라운드 서비스 type 수정

---

backend/src/test/java/com/ody/common/BaseRepositoryTest.java

close #1044
<br>
- CI를 도는 환경은 github가 빌려준 미국 서버 기준이기에 타임존에 따라 쿼리 에러가 발생
- 따라서 default timezone을 서울로 설정함으로써 CI에서 에러가 나지 않도록 수정
- 이걸해야 정상배포가 가능함!
<br>
<br>

fix: 정상배포를 위한 테스트 타임존 설정
