- backend/src/main/java/com/ody/common/domain/BaseEntity.java
- backend/src/main/java/com/ody/mate/domain/Mate.java
- backend/src/main/java/com/ody/meeting/domain/Coordinates.java
- backend/src/main/java/com/ody/meeting/domain/Location.java
- backend/src/main/java/com/ody/meeting/domain/Meeting.java
- backend/src/main/java/com/ody/member/domain/Member.java
- backend/src/main/java/com/ody/notification/domain/Notification.java
- backend/src/main/java/com/ody/notification/domain/NotificationType.java
close #7
<br>
Meeting, Mate, Member, Notification 엔티티 구현
<br>
<br>
> feat: 엔티티 구현

- backend/src/main/java/com/ody/mate/domain/controller/MateController.java
- backend/src/main/java/com/ody/mate/domain/controller/MateControllerSwagger.java
- backend/src/main/java/com/ody/mate/domain/dto/MateSaveRequest.java
- backend/src/main/java/com/ody/meeting/controller/MeetingController.java
- backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
- backend/src/main/java/com/ody/meeting/dto/MeetingSaveRequest.java
- backend/src/main/java/com/ody/meeting/dto/MeetingSaveResponse.java
close #10
<br>
Swagger API로 모임 참여 API 문서화
<br>
<br>
> docs: 모임 참여 API 문서화

- backend/src/main/java/com/ody/mate/domain/controller/MateController.java
- backend/src/main/java/com/ody/mate/domain/controller/MateControllerSwagger.java
- backend/src/main/java/com/ody/meeting/controller/MeetingController.java
- backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
- backend/src/main/java/com/ody/meeting/dto/request/MeetingSaveRequest.java
- backend/src/main/java/com/ody/meeting/dto/response/MateResponse.java
- backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponse.java
- backend/src/main/java/com/ody/meeting/dto/response/MeetingSaveResponses.java
close #12 
<br>
Swagger API를 사용한 참여 모임 목록 조회 API 문서화 (/meetings/me)
<br>
<br>
> docs: 참여중인 모임 목록 조회 API 문서화

- backend/src/main/java/com/ody/notification/controller/NotificationController.java
- backend/src/main/java/com/ody/notification/controller/NotificationControllerSwagger.java
- backend/src/main/java/com/ody/notification/dto/request/NotificationSaveResponse.java
- backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
close #9 
<br>
Swagger API로 로그 목록 조회 API 문서화
<br>
<br>
> docs: 로그 목록 API 문서화

- .github/workflows/backend-ci-dev.yml
#19 
<br>
backend develop CI 파이프라인 구축
<br>
<br>
> chore: backend ci 스크립트 작성

- android/app/src/main/res/values-night/themes.xml
- android/app/src/main/res/values/themes.xml
> feat: Status바 추가

- android/app/build.gradle.kts
- android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchDialog.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/destination/DestinationFragment.kt
- android/app/src/main/res/layout/dialog_address_search.xml
- android/app/src/main/res/layout/fragment_destination.xml
- android/app/src/main/res/values/colors.xml
- android/app/src/main/res/values/dimens.xml
- android/app/src/main/res/values/strings.xml
close #18 
<br>
<br>
https://github.com/user-attachments/assets/15282250-cd76-44dc-8821-6d86ae9391fc
<br>
이슈가 너무 커서 잘게 쪼갤게용
지금은 EditText 클릭하면 웹뷰 다이얼로그 띄워주는 것만 했고, 웹뷰는 아직 연결 안 한 상태!
> feat: 주소 검색 화면 구현

- .github/workflows/android-ci-dev.yml
> chore: android ci 구축

- .idea/misc.xml
- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
- android/app/src/main/java/com/woowacourse/ody/data/local/FCMService.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/MemberService.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/RetrofitClient.kt
- android/build.gradle.kts
- android/gradle.properties
- android/gradle/libs.versions.toml
close #31
<br>
<br>
<br>
local.properties에 아래와 같이 서버 주소를 추가해 주세요. 
서버 주소는 저희 서버 api 주소 입력해주시면 됩니다.
google-services.json도 app폴더 내에 추가해주시면 됩니다.
> feat: FCM 구현

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/woowacourse/ody/presentation/adapter/InfoViewPagerAdapter.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/BackListener.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/InfoListener.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoActivity.kt
- android/app/src/main/res/layout/activity_join_info.xml
- android/app/src/main/res/layout/activity_meeting_info.xml
- android/app/src/main/res/layout/toolbar_back.xml
close #22 
<br>
<br>
[Screen_recording_20240723_145123.webm](https://github.com/user-attachments/assets/f6a21e7a-1cac-4d35-9796-5e99ed7baf26)
<br>
> feat: 모임 참여 시 프래그먼트들 연결하는 뷰페이저

- .github/workflows/android-ci-dev.yml
- android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
> chore: android ci 필드 추가

- android/app/src/main/java/com/woowacourse/ody/presentation/date/MeetingDateFragment.kt
- android/app/src/main/res/layout/fragment_meeting_date.xml
- android/app/src/main/res/values/strings.xml
close #36 
<br>
<br>
[Screen_recording_20240723_174626.webm](https://github.com/user-attachments/assets/77dd233e-3673-483f-a9c2-f3c453276441)
<br>
> feat: 약속 날짜 입력 화면

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/CodeCopyListener.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/LogsActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/LogsListener.kt
- android/app/src/main/res/drawable/bottom_sheet_radius_25.xml
- android/app/src/main/res/layout/activity_logs.xml
- android/app/src/main/res/layout/bottom_sheet_code_copy.xml
- android/app/src/main/res/values/strings.xml
close #32 
<br>
<br>
[Screen_recording_20240723_234302.webm](https://github.com/user-attachments/assets/8cf820b8-df9d-4de3-bec3-71c69901a026)
<br>
- 색 구별이 잘 돼서 바텀시트에 stroke 넣었는데 어떤지 궁금합니다.
- 일단 임시로 "ABCD1234" 텍스트로 클립보드 복사 테스트를 하고 있습니다. 추후에 실제 초대 코드를 사용합니다.
- 클립보드 화면이 스낵바를 가려서 추후에 스낵바를 위 쪽에 뜨게 하려고 합니다.
> feat: 초대 코드 복사 bottom dialog

- android/app/src/main/res/layout/dialog_address_search.xml
close #94 
<br>
<br>
[Screen_recording_20240724_110301.webm](https://github.com/user-attachments/assets/7e2ba55f-8dda-4909-b65b-1f109a5af58e)
<br>
> feat: 다이얼로그 위치 조정

- .github/workflows/android-ci-dev.yml
- .github/workflows/backend-cicd-dev.yml
- .gitmodules
- backend/src/test/java/com/ody/common/validator/FutureOrPresentDateTimeValidatorTest.java
> feat: 서브모듈 환경 구축

- android/app/build.gradle.kts
- android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
- android/app/src/main/java/com/woowacourse/ody/data/local/db/OdyDatastore.kt
- android/gradle/libs.versions.toml
> feat: 초대 코드 Preference dataStore 세팅

- backend/src/main/java/com/ody/meeting/service/InviteCodeGenerator.java
- backend/src/test/java/com/ody/meeting/service/InviteCodeGeneratorTest.java
close #56
<br>
모임 초대 코드를 meetingId를 이용해 인코딩해 생성하고
decoding해 meetingId를 찾는다.
<br>
<br>
> feat: 모임 초대 코드 생성 기능 추가

- android/app/src/main/java/com/woowacourse/ody/data/remote/RetrofitClient.kt
> feat: 서버 헤더 형식 변경

- backend/src/main/java/com/ody/common/exception/GlobalExceptionHandler.java
- backend/src/main/java/com/ody/common/exception/OdyException.java
- backend/src/main/java/com/ody/mate/domain/Mate.java
- backend/src/main/java/com/ody/mate/domain/Nickname.java
- backend/src/main/java/com/ody/meeting/domain/Location.java
- backend/src/test/java/com/ody/mate/domain/NicknameTest.java
- backend/src/test/java/com/ody/meeting/domain/LocationTest.java
close #59
<br>
**1. `FutureOrPresentDateTimeValidator` 리뷰 미반영**
이에 대한 리뷰는 카키가 선택적으로 반영하는 게 좋을 듯해 남겨두었어요 (https://github.com/woowacourse-teams/2024-ody/pull/68#discussion_r1687671949, https://github.com/woowacourse-teams/2024-ody/pull/68#discussion_r1687690035, https://github.com/woowacourse-teams/2024-ody/pull/68#discussion_r1687694200)
카키가 새로운 이슈를 만들어도 되고 현재 이슈에 커밋해서 함께 머지해도 될 것 같아요
**2. 어노테이션 정렬 컨벤션 논의**
현재 컨벤션 개선하면 좋을 것 같은데 [조조의 리뷰](https://github.com/woowacourse-teams/2024-ody/pull/68#discussion_r1687983524)에서 이어서 이야기 나눴으면 좋겠어요!
<br> 
**1. 모임 닉네임 중복 불가 구현 지연**
`모임 내 닉네임은 중복될 수 없다.` 요구사항은 작업의 편의성을 위해 [feat: 출발 시간 알림 구현](https://github.com/woowacourse-teams/2024-ody/pull/60)이 머지된 후에 https://github.com/woowacourse-teams/2024-ody/issues/81 이슈에서  작업하겠습니다
**2. 위도, 경도 검증 로직 추가**
기능 명세서 상에 없는 …
> feat: 닉네임, 출발지 입력

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/woowacourse/ody/presentation/date/MeetingDateFragment.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/destination/MeetingDestinationFragment.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/LogsActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/NotificationLogActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/startingpoint/JoinStartingPointFragment.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/time/MeetingTimeFragment.kt
> feat: 스낵바 위치 조정

- .github/workflows/backend-cd-dev.yml
- .github/workflows/backend-ci-dev.yml
close #115
<br>
CI 스크립트 : develop에 push/pull-request 시, feature/XX를 기준으로 build
CD 스크립트 : develop에 merge시, develop 기준 build
<br>
<br>
> feat: CI/CD 스크립트 분리

- backend/src/main/java/com/ody/mate/service/MateService.java
- backend/src/test/java/com/ody/mate/service/MateServiceTest.java
> feat: 모임 내 닉네임 중복 검증

- android/app/src/main/java/com/woowacourse/ody/data/local/fake/FakeMeetingRepository.kt
- android/app/src/main/java/com/woowacourse/ody/data/model/Mapper.kt
- android/app/src/main/java/com/woowacourse/ody/data/model/meeting/MeetingRequest.kt
- android/app/src/main/java/com/woowacourse/ody/data/model/meeting/MeetingResponse.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/repository/DefaultMeetingRepository.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/service/MeetingService.kt
- android/app/src/main/java/com/woowacourse/ody/domain/Meeting.kt
- android/app/src/main/java/com/woowacourse/ody/domain/repository/MeetingRepository.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteViewModelFactory.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetinglog/LogsActivity.kt
> feat: 모임 개설 서버 연결

- backend/src/main/java/com/ody/meeting/controller/MeetingController.java
- backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
- backend/src/main/java/com/ody/meeting/service/MeetingService.java
- backend/src/test/java/com/ody/common/Fixture.java
- backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
- backend/src/test/java/com/ody/meeting/repository/MeetingRepositoryTest.java
- backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
close #117 
<br>
- 테스트 간섭이 생기는 두 테스트를 우선 Disabled 처리 후 PR 요청합니다.
- NotificationRepositoryTest :  findAllMeetingLogsById()
- MeetingControllerTest: findMine
<br>
<br>
> feat: 특정 회원이 참여한 모임 목록 조회 API 구현

- backend/src/test/java/com/ody/common/BaseServiceTest.java
- backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
- backend/src/test/java/com/ody/util/InviteCodeGeneratorTest.java
> fix: backend merge bug fix

- android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeNavigateAction.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
> fix: 초대 코드 입력 성공 시 참여 화면으로 이동하도록 수정

- android/app/src/main/java/com/woowacourse/ody/data/model/join/JoinRequest.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/repository/DefaultJoinRepository.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/service/JoinService.kt
- android/app/src/main/java/com/woowacourse/ody/domain/repository/JoinRepository.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/completion/JoinCompleteViewModelFactory.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
> feat: 모임 참여 서버 연결

- android/app/src/main/java/com/woowacourse/ody/data/local/fake/FakeNotificationLogRepository.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/repository/DefaultNotificationLogRepository.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/service/NotificationService.kt
- android/app/src/main/java/com/woowacourse/ody/domain/repository/NotificationLogRepository.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/notificationlog/NotificationLogViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashViewModelFactory.kt
> feat: 참여중인 모임 목록 조회

- android/app/src/main/java/com/woowacourse/ody/data/remote/FCMService.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/completion/MeetingCompletionActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/date/MeetingDateFragment.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/joininfo/JoinInfoActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetinginfo/MeetingInfoViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/time/MeetingTimeFragment.kt
- android/app/src/main/res/drawable/bottom_sheet_radius_25.xml
- android/app/src/main/res/layout/bottom_sheet_code_copy.xml
- android/app/src/main/res/layout/fragment_join_starting_point.xml
- android/app/src/main/res/layout/fragment_meeting_destination.xml
close #138 
<br>
<br>
<br>
커밋 하나하나 연관성이 없고 너무 자잘해서, files changed로 보면 리뷰하기 힘들 수 있어요!!
커밋 하나씩 보면서 리뷰해주시면 감사하겠습니다~!
> fix: 자잘한 ux 버그 다수 수정

- backend/src/main/java/com/ody/notification/service/FcmPushSender.java
- backend/src/main/java/com/ody/notification/service/FcmSubscriber.java
close #147 
<br>
FCM 토픽 Malformed topic name 에러 해결
<br>
<br>
> fix: FCM 토픽 Malformed topic name 에러 해결

- backend/src/main/java/com/ody/notification/service/FcmPushSender.java
- backend/src/main/java/com/ody/notification/service/NotificationService.java
> fix: Malformed topic name 에러 해결

- android/app/src/main/java/com/woowacourse/ody/presentation/date/MeetingDateFragment.kt
- android/app/src/main/res/layout/fragment_meeting_date.xml
close #154 
<br>
<br>
[Screen_recording_20240725_171901.webm](https://github.com/user-attachments/assets/f6d7a548-5d3e-4174-ba05-5d30c3e09c30)
<br>
> fix: 달력 월말 날짜 선택 안되는 버그 수정

- backend/src/main/java/com/ody/notification/domain/Notification.java
- backend/src/main/java/com/ody/notification/dto/request/FcmSendRequest.java
- backend/src/main/java/com/ody/notification/service/FcmPushSender.java
- backend/src/main/java/com/ody/notification/service/NotificationService.java
- backend/src/test/java/com/ody/notification/service/FcmEventSchedulerTest.java
> fix: 알림 전송 예약 시점이 아닌 전송 시점에 상태 변경

- backend/src/main/java/com/ody/meeting/controller/MeetingController.java
- backend/src/main/java/com/ody/meeting/repository/MeetingRepository.java
- backend/src/main/java/com/ody/meeting/service/MeetingService.java
- backend/src/test/java/com/ody/meeting/repository/MeetingRepositoryTest.java
> feat: 초대코드 존재유무 검증로직 구현

- android/app/src/main/java/com/woowacourse/ody/data/model/Mapper.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/splash/SplashActivity.kt
> fix: 스플래쉬 딜레이 수정

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/woowacourse/ody/presentation/common/Event.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/common/MutableSingleLiveData.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/common/SingleLiveData.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/creation/time/MeetingTimeFragment.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/join/complete/JoinCompleteViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/join/departure/JoinDepartureFragment.kt
> refactor: manifest tools 속성 제거

- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MatesEtaResponseMapper.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MeetingRequestMapper.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MeetingResponseMapper.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/request/MatesEtaRequest.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MateEtaResponse.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MatesEtaResponse.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/MeetingService.kt
- android/app/src/main/java/com/woowacourse/ody/domain/model/EtaType.kt
- android/app/src/main/java/com/woowacourse/ody/domain/model/MateEta.kt
- android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/MeetingRepository.kt
> feat: 유저 현황 화면 api v1 연결

- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/adapter/MateEtaViewHolder.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/adapter/MateEtasAdapter.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/listener/MissingToolTipListener.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/EtaDurationMinuteTypeUiModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/EtaTypeUiModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/EtaTypeUiModelMapper.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModelMapper.kt
- android/app/src/main/res/layout/item_eta_dashboard.xml
- android/app/src/main/res/layout/layout_missing_tooltip.xml
close #202
<br>
<br>
<br>
아 branch rename했더니 기존 pr이 close 됐네요;; 다시 pr 올립니다.. 
해음은 리뷰 다시 해주시고 차람은 approve 다시 부탁드려요!
해음이 확인해주셔야 할 리뷰 반영 commit -> [f7496cb](https://github.com/woowacourse-teams/2024-ody/pull/265/commits/f7496cbee412d4a909195083c34a01599bde03ea), [5cb81cc](https://github.com/woowacourse-teams/2024-ody/pull/265/commits/5cb81cc7f47da5d3e66e951f6389db62b58f4058)
[기존 pr 링크](https://github.com/woowacourse-teams/2024-ody/pull/264)
> feat: 유저 현황 화면 리스트 어댑터 구현

- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/join/response/JoinResponse.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/join/response/JoinResponseMapper.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MeetingResponseMapper.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultJoinRepository.kt
- android/app/src/main/java/com/woowacourse/ody/domain/model/ReserveInfo.kt
- android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/JoinRepository.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModel.kt
> refactor: v1/mates 응답값 수정

- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/intro/IntroActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetinglist/MeetingsBindingAdapter.kt
- android/app/src/main/res/layout/item_meeting.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
- android/gradle/libs.versions.toml
close #216 
<br>
<br>
[Screen_recording_20240806_195751.webm](https://github.com/user-attachments/assets/cc400067-8fc8-4f70-9cfc-94ea372c6db3)
<br>
> feat: 위치 권한 받아오는 기능 구현

- backend/src/main/java/com/ody/eta/service/EtaService.java
close #285 
<br>
update 미반영 오류 문제 해결
<br>
<br>
> fix: update 미반영 오류 문제 해결

- android/app/src/main/java/com/woowacourse/ody/data/local/repository/DefaultMatesEtaRepository.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModel.kt
> fix: 유저 현황표 폴링 방식 수정

- backend/src/main/java/com/ody/eta/domain/Eta.java
- backend/src/main/java/com/ody/eta/domain/EtaStatus.java
- backend/src/main/java/com/ody/eta/dto/response/MateEtaResponse.java
- backend/src/main/java/com/ody/eta/service/EtaService.java
- backend/src/main/java/com/ody/meeting/controller/MeetingController.java
- backend/src/main/java/com/ody/meeting/service/MeetingService.java
#244 
close #288 
<br>
* 약속 참여자 ETA 조회시, 행방불명 요청시 500에러 해결 (위도 경도 null인 경우 처리)
* MateEtaResponse가 ARRIVED면 소요시간 0, MISSING이면 -1, ARRIVAL_SOON이면 1 응답되도록 수정.
* polling 요청 받는 중간에 MateEtaRequest의 위도 경도가 잘못됐을 경우에 대한 예외도 처리.
* MeetingController가 EtaService를 직접 호출하도록 코드 수정
<br>
<br>
> refactor: 데모데이 이슈 문제 해결 

- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardActivity.kt
- android/app/src/main/res/layout/activity_eta_dashboard.xml
close #297 
<br>
<br>
https://github.com/user-attachments/assets/e8d1a520-5178-4dc9-93d9-877862b2765b
<br>
첨부한 영상 보시면, 처음으로 값이 변경될 때만 깜빡이고 이후에는 깜빡이지 않습니다!
이것도 한 줄로 해결되네요..ㄷㄷ recyclerView 부분 구현하실 때 `itemAnimator = null` 속성 설정해주는 거 참고해주시면 좋을 것 같아요.
> fix: 리스트 깜빡임 현상 해결

- android/app/src/main/res/layout/activity_notification_log.xml
close #312
<br>
<br>
https://github.com/user-attachments/assets/fd98c99a-3dd3-48ae-b180-3fa2075671d8
<br>
-1일이 나타나는 문제는 #307 번 pr 올리며 수정했습니다.
그리고 로그화면 깜빡임 현상 문제는 리스트가 깜빡이는 문제라 생각해서 일단 itemAnimator에 null을 넣어두긴 했는데,
제가 알고 있는게 맞나요?
> fix: 약속 로그 관련 수정 사항

- backend/src/main/java/com/ody/eta/domain/EtaStatus.java
- backend/src/main/java/com/ody/eta/dto/response/MateEtaResponse.java
- backend/src/test/java/com/ody/eta/domain/EtaStatusTest.java
> fix: 행방불명 오류 해결

- backend/src/main/java/com/ody/eta/dto/response/MateEtaResponse.java
- backend/src/main/java/com/ody/eta/service/EtaService.java
close #322 
<br>
요청을 보낸 사람의 닉네임으로 행방불명 상태 여부 판단하여 MateEtaResponses 응답하도록 수정
<br>
<br>
> fix: 해결되지 않은 행방불명 오류 해결

- android/app/src/main/java/com/woowacourse/ody/data/local/service/EtaDashBoardWorker.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/join/request/JoinRequestMapper.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MeetingRequestMapper.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
> fix: compress 메서드 수정, gps 온오프 확인

- backend/src/main/java/com/ody/eta/domain/EtaStatus.java
close #324 
<br>
eta상태 매핑 로직 내에 조건문 수정
<br>
<br>
> fix: 도착한 상태인 사람의 소요시간이 -1로 반환되고 있는 문제 해결

- android/app/src/main/res/layout/item_meeting_catalog.xml
> fix: 미팅 목록 아이템 접기/펴기 버튼 터치영역 늘리기

- android/app/build.gradle.kts
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardViewModel.kt
- android/app/src/test/java/com/woowacourse/ody/fake/FakeMatesEtaRepository.kt
- android/app/src/test/java/com/woowacourse/ody/util/CoroutinesTestExtension.kt
- android/app/src/test/java/com/woowacourse/ody/util/InstantTaskExecutorExtension.kt
- android/app/src/test/java/com/woowacourse/ody/util/TestUtil.kt
- android/app/src/test/java/com/woowacourse/ody/viewmodel/EtaDashBoardViewModelTest.kt
- android/gradle/libs.versions.toml
> feat: EtaDashboardViewModelTest 구현

- .github/workflows/backend-cd-dev.yml
- .github/workflows/backend-ci-dev.yml
- backend/build.gradle
close #253 
<br>
- CI : develop에 pull request가 열렸을 때
- CD : develop에 push가 발생했을 때
<br>
<br>
- backend 한정 스크립트 입니다.
> docs: test coverage report 스크립트 추가

- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
> config: 앱 출시를 위한 수정

- android/app/build.gradle.kts
- android/build.gradle.kts
- android/gradle/libs.versions.toml
> refactor: 버전 카탈로그에 맞게 수정

- android/app/src/main/java/com/woowacourse/ody/OdyApplication.kt
- android/app/src/main/java/com/woowacourse/ody/data/local/service/EtaDashboardWorker.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchDialog.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchViewModelFactory.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/common/analytics/AnalyticsExtension.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/common/analytics/AnalyticsHelper.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/common/analytics/FirebaseAnalyticsHelper.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModelFactory.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModelFactory.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModelFactory.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModelFactory.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogViewModelFactory.kt
close #360 
<br>
<br>
<br>
ㅎㅎ 진작할 걸~ 지송 감사요
> refactor: 로깅 관련 코드 리팩터링

- android/app/src/main/java/com/woowacourse/ody/data/local/service/EtaDashboardWorker.kt
> fix: Last Location null 발생

- android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetings/model/MeetingUiModelMapper.kt
- android/app/src/test/java/com/woowacourse/ody/TestFixtures.kt
- android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
- android/app/src/test/java/com/woowacourse/ody/viewmodel/MeetingsViewModelTest.kt
close #397
<br>
<br>
<br>
#396 번 이슈 PR 먼저 머지 후 거기 있는 Fixture를 적용해보면 좋을것 같은데 어떠신가요
> test: MeetingsViewModel 테스트 작성

- android/app/src/test/java/com/woowacourse/ody/presentation/address/AddressSearchViewModelTest.kt
- android/app/src/test/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModelTest.kt
- android/app/src/test/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModelTest.kt
- android/app/src/test/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModelTest.kt
- android/app/src/test/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModelTest.kt
- android/app/src/test/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModelTest.kt
close #402 
<br>
<br>
<br>
뷰모델 테스트를 프로덕션 코드와 동일한 패키지 계층에 위치시켰습니다~!
> chore: unitTest 패키지 구조 수정

- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
- android/app/src/main/res/anim/bounce_duration_500.xml
- android/app/src/main/res/layout/item_eta_dashboard.xml
close #382 
<br>
<br>
[Screen_recording_20240816_135700.webm](https://github.com/user-attachments/assets/464fcb32-0be5-41ca-a6b5-367e8aa41601)
<br>
> design: 현황 화면 뱃지 애니메이션 추가

- .github/workflows/backend-cd-dev.yml
- .github/workflows/backend-cd-prod.yml
- .github/workflows/backend-ci-prod.yml
- backend/Dockerfile
- backend/src/main/resources/application.yml
- backend/src/main/resources/logback-spring.xml
close #370 
<br>
- 프로덕션 용 서비스 코드를 프로덕션용 EC2에 배포
- main에 push 이벤트 발생 시, cd-prod 워크플로우 실행
- 프로덕션 EC2 대시보드 생성
<br>
<br>
> chore: 프로덕션 서버에 서비스 띄우기

- android/app/build.gradle.kts
- android/app/proguard-rules.pro
close #414 
<br>
<br>
<br>
난독화 관련 간단히 정리했는데 참고만 부탁드려여
https://www.notion.so/R8-c6a83d1baf3c456392ffcd04a5dd0b2f
난독화 때문에 앱 터지는지 계속 트래킹하고 싶어서 일단 디버그 모드 빌드 시에도 난독화 적용되도록 추가했어요 ! 
생각보다 너무 간단해서 당황 ㄷㄷ
> config: 난독화 적용

- android/app/src/main/java/com/woowacourse/ody/data/local/entity/eta/MatesEtaInfoResponse.kt
- android/app/src/main/java/com/woowacourse/ody/data/local/repository/DefaultMatesEtaRepository.kt
- android/app/src/main/java/com/woowacourse/ody/data/local/service/EtaDashboardWorker.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MatesEtaResponseMapper.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MateEtaResponse.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/response/MatesEtaResponse.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/MeetingService.kt
- android/app/src/main/java/com/woowacourse/ody/domain/model/MateEta.kt
- android/app/src/main/java/com/woowacourse/ody/domain/model/MateEtaInfo.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModelMapper.kt
- android/app/src/test/java/com/woowacourse/ody/TestFixtures.kt
close #413 
<br>
<br>
<br>
서버 api 호출해서 오류 없는 것까지 확인했습니다!
생각보다 너무 간단해서 당황 ㄷㄷ
> refactor: ETA 조회 API 응답 수정

- android/app/proguard-rules.pro
- android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchDialog.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/address/AddressSearchViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/common/BaseViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/common/LoadingDialog.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/creation/MeetingCreationViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/invitecode/InviteCodeViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/join/MeetingJoinViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
- android/app/src/main/res/layout/dialog_loading.xml
close #429 
<br>
<br>
https://github.com/user-attachments/assets/7b8139e5-1bcf-47a4-9bc3-ae7c4fdab69f
https://github.com/user-attachments/assets/1d8be59d-4538-40c9-abbe-ddac9e3be9ab
<br>
지금은 progressbar가 좀 못생겼긴 한데... 일단!!! 코드만 봐주십쇼 ㅋ
> feat: 로딩 중 ProgressBar 다이얼로그 띄우는 기능 구현

- android/app/src/main/java/com/woowacourse/ody/presentation/common/image/ImageShareContent.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/common/image/KakaoImageShareHelper.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/listener/ShareListener.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogFragment.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/log/listener/InviteCodeCopyListener.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/log/listener/MenuListener.kt
- android/app/src/main/res/layout/fragment_eta_dashboard.xml
- android/app/src/main/res/layout/fragment_notification_log.xml
- android/app/src/main/res/layout/toolbar_eta_dashboard.xml
- android/app/src/main/res/layout/toolbar_notification_log.xml
- android/app/src/main/res/values/strings.xml
close #383
<br>
<br>
https://github.com/user-attachments/assets/cec17068-826c-403b-9338-97f90a480ac0
안드로이드 폰에서는 위처럼 보입니다!
<br>
현황 이미지 공유와 유사한 코드입니다~!
> feat: 초대 코드 카카오톡 공유하기 기능 구현

- android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
> refactor: Firebase Analytics 로깅을 비동기로 남기도록 수정

- android/app/src/main/java/com/woowacourse/ody/presentation/common/binding/BindingFragment.kt
close #440
<br>
<br>
<br>
에러가 터지는군요.. 좀 더 꼼꼼히 확인할게요~!
> fix: fragment 로깅 찍는 시점 수정

- android/app/src/main/AndroidManifest.xml
close #444
<br>
<br>
<br>
@aprilgom 로그인 쪽 PR merge할 때 이 부분 꼭 반영 부탁드려요!
하나의 인텐트 필터에 MAIN, LAUNCHER 속성과 <data>가 함께 존재하면 앱이 사라진다고 합니다.
인텐트 필터 두개로 분리해주세요
> fix: 앱이 메뉴에서 보이지 않는 이슈 해결

- .github/workflows/backend-cd-dev.yml
- .github/workflows/backend-cd-prod.yml
- .github/workflows/backend-ci-dev.yml
- .github/workflows/backend-ci-prod.yml
- backend/docker-compose.yml
close #443 
<br>
- H2 메모리 DB를 사용하던 Dev 서버에서 MySQL DB를 사용하도록 변경
- CI 워크플로에서 Build 과정을 없애고 Test를 실행하도록 변경
<br>
<br>
- EC2 운영 비용만 1달 42.34 USD(약 56,000원) 예상
> chore: dev 서버 DB MySQL 교체 작업

- backend/build.gradle
- backend/src/main/resources/application.yml
- backend/src/main/resources/schema.sql
> fix: develop 스키마 validation 오류 해결 BE BUG

- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/mapper/MeetingRequestMapper.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/entity/meeting/request/NudgeRequest.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/repository/DefaultMeetingRepository.kt
- android/app/src/main/java/com/woowacourse/ody/data/remote/core/service/MeetingService.kt
- android/app/src/main/java/com/woowacourse/ody/domain/model/Nudge.kt
- android/app/src/main/java/com/woowacourse/ody/domain/repository/ody/MeetingRepository.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/notification/NotificationHelper.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/listener/NudgeListener.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModel.kt
- android/app/src/main/java/com/woowacourse/ody/presentation/room/etadashboard/model/MateEtaUiModelMapper.kt
- android/app/src/main/res/values/strings.xml
- android/app/src/test/java/com/woowacourse/ody/fake/FakeMeetingRepository.kt
- android/app/src/test/java/com/woowacourse/ody/presentation/room/MeetingRoomViewModelTest.kt
close #423 
<br>
재촉하기 api 수정
<br>
[Screen_recording_20240822_140405.webm](https://github.com/user-attachments/assets/a9d88094-79ff-4a27-a096-d36581736f2a)
<br>
> feat: 재촉하기 알림에 닉네임이 보이게 변경

- android/app/src/main/java/com/woowacourse/ody/presentation/room/log/NotificationLogFragment.kt
close #469 
<br>
📝 작업 내용
<br>
<br>
> design: 초대코드 공유 이미지 링크 수정

- android/app/build.gradle.kts
- android/app/src/main/java/com/woowacourse/ody/presentation/meetings/MeetingsActivity.kt
- android/app/src/main/res/values/strings.xml
> feat: 약속 리스트에서 뒤로가기 2번 하면 나갈 수 있는 기능 구현

- backend/src/main/java/com/ody/member/controller/MemberController.java
- backend/src/main/java/com/ody/member/controller/MemberControllerSwagger.java
close #476
<br>
<br>
<br>
‼️ 올리브에게 <ins>**6일 오후 3시까지**</ins> 문서를 제공해주기로 해서 그 전에 pr을 검토해주실 수 있을까요?
> docs: 회원 삭제 API 문서화

- .github/workflows/android-ci-dev.yml
- android/app/build.gradle.kts
- android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
close #495 
<br>
<br>
[Screen_recording_20240909_144208.webm](https://github.com/user-attachments/assets/b3b51163-4217-469f-952a-0fe279f23931)
<br>
> feat: 설정 화면에서 개인정보 처리 방침, 서비스 이용 약관 링크 연결

- backend/src/main/resources/application.yml
close #517
<br>
common.yml 내 odsay.url을 null로 읽어와서 에러 발생
<br>
<br>
> fix: dev 서버 약속 생성 불가

- backend/src/main/java/com/ody/common/filter/LoggingFilter.java
- backend/src/main/java/com/ody/eta/domain/EtaStatus.java
- backend/src/main/resources/logback-spring.xml
close #502
<br>
- MDC 도입
- 지각한 참여자 로그 출력
**참고**: 
-  현재 프로덕션 코드와 로깅을 위한 코드가 혼재되어 있으나, [추후 이슈](https://github.com/woowacourse-teams/2024-ody/issues/503)에서 개선할 예정입니다.
<br>
<br>
- 프로덕션 코드와 로깅 코드 분리를 위한 방안을 찾지 못했습니다. 어떻게 하면 좋을까요? 🤔 
- 유저 행동 로그와 운영 로그를 분리하기 위해서 현재는 "report_XXX" prefix를 활용해 임시적으로 구분하고 있습니다. 어떤 방식으로 구분하면 좋을지 같이 고민해주면 감사할 것 같아요.
> chore: logging 향상을 위한 MDC 도입

- backend/src/main/java/com/ody/member/service/MemberService.java
- backend/src/main/java/com/ody/notification/dto/response/NotiLogFindResponse.java
close #557
<br>
지워진 메서드가 있어서 코드가 깨졌는데 제대로 확인을 안 하고 #540 PR을 머지해버렸습니다..
<br>
<br>
> fix: Nickname 객체 로직 정리 merge conflict 발생

- backend/src/main/java/com/ody/route/config/RouteProperties.java
- backend/src/main/resources/common.yml
close #556 
<br>
오늘 오전 8:33 Odsay api 요청 횟수 초과로 5일간 정지됨
개인 Odsay 계정으로 key 발급받아 교체함 -> 추후 정지 풀리면 다시 교체 예정
<br>
<br>
> fix: Odsay API 요청 정지 복구

- backend/src/main/java/com/ody/notification/domain/Notification.java
- backend/src/main/java/com/ody/notification/service/NotificationService.java
- backend/src/main/java/com/ody/route/service/OdsayRouteClient.java
close #567 
<br>
- 입장 알림 전송 에러 문제 해결
- 알림 예약 시 어떤 타입에 대한 알림인지 로그 필드 추가
<br>
<br>
> fix: 입장 알림 전송 에러 문제 해결

- android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/fcm/service/FCMService.kt
- android/app/src/main/java/com/mulberry/ody/domain/model/NotificationType.kt
- android/app/src/main/java/com/mulberry/ody/presentation/notification/NotificationHelper.kt
- android/app/src/main/res/values/strings.xml
> feat: 푸시 메세지를 클릭했을 때 앱 내로 접속

- android/app/src/main/java/com/mulberry/ody/di/ActivityModule.kt
- android/app/src/main/java/com/mulberry/ody/di/AppModule.kt
- android/app/src/main/java/com/mulberry/ody/di/ServiceModule.kt
> fix: hilt 적용된 뒤 초대하기, 리프래시 토큰 안되는 버그

- backend/src/main/resources/db/migration/V2__alter_notification_type_check.sql
close #584 
<br>
- flyway V2 notification 체크 제약 조건 제거 구문 제거
이전 체크 제약조건을 제거하고 새로운 제약조건으로 추가하려 했지만
이미 이전 체크 제약조건이 DB상에 제거 되어 있던 상황이라 에러 발생해서 추가하는 쿼리만 남겨놨어요
<br>
<br>
> chore: 병합 충돌로 인한 CI 깨짐 해결

- backend/src/main/java/com/ody/common/config/ReplicationType.java
close #591 
READ / WRITE DB 연결 조건 수정
<br>
<br>
<br>
> hotfix: READ / WRITE DB 연결 조건 수정

- android/app/src/main/res/layout/item_meeting_catalog.xml
- android/app/src/main/res/values/strings.xml
> design: 대중교통 멘트 추가

- android/app/src/main/java/com/mulberry/ody/data/local/repository/DefaultMatesEtaRepository.kt
- android/app/src/main/java/com/mulberry/ody/domain/repository/ody/MatesEtaRepository.kt
- android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingViewModel.kt
- android/app/src/test/java/com/mulberry/ody/fake/FakeMatesEtaRepository.kt
> refactor: 회원 탈퇴 시 예약된 스케줄링 모두 삭제

- android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardWorker.kt
> fix: gps Location이 null이 나오는 버그 수정

- backend/src/main/resources/common.yml
close #607 
<br>
DB까지 actuator가 헬스 체크하지 않도록 수정
<br>
<br>
> hotfix: DB health check 하지 않도록 수정

- backend/src/main/resources/common.yml
close #608
<br>
odsay api key 갱신
<br>
<br>
> hotfix: odsay api key 오류 해결

- backend/src/main/resources/db/migration/V3__alter_character_set.sql
> hotfix: character set 변경 SQL syntax 에러

- android/app/build.gradle.kts
- android/app/proguard-rules.pro
close #625
<br>
<br>
<br>
일단은 main이 아닌 develop에 머지되는 PR입니다.
cd 타서 배포하지 않고 play console에 직접 업로드 했어요!
> release: 안드로이드 1.0.0 출시

- android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardWorker.kt
- android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/address/KakaoAddressRepository.kt
- android/app/src/main/java/com/mulberry/ody/di/AppModule.kt
- android/app/src/main/java/com/mulberry/ody/presentation/common/gps/GeoLocationHelper.kt
- android/app/src/main/java/com/mulberry/ody/presentation/common/gps/GpsHelper.kt
- android/app/src/main/java/com/mulberry/ody/presentation/common/gps/LocationHelper.kt
- android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
- android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
- android/app/src/test/java/com/mulberry/ody/fake/FakeLocationHelper.kt
- android/app/src/test/java/com/mulberry/ody/presentation/join/MeetingJoinViewModelTest.kt
close #590 
<br>
<br>
<br>
GpsHelper에서 위치 권한이 허용되어 있는지, gps를 켰는지 확인안하는 이유가 Location 찾다가 exception이 발생하면 null을 반환하기 때문입니다.
> refactor: 현재 위치 가져오는 객체 생성 및 분리

- android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
- android/app/src/main/res/drawable/ic_current_location.xml
- android/app/src/main/res/layout/activity_meeting_join.xml
close #623 
<br>
<br>
- 지원하지 않는 지역일 때
[Screen_recording_20241004_154454.webm](https://github.com/user-attachments/assets/cd5cdb1e-c362-483f-8e59-e62dbc538633)
- 지원하는 지역일 때
[Screen_recording_20241004_154626.webm](https://github.com/user-attachments/assets/d74f33ea-791a-46d0-ab92-1a450fef3648)
<br>
> feat: 출발지 입력할 때 현재 위치 눌러서 가져오기로 변경

- android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeActivity.kt
- android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeViewModel.kt
- android/app/src/main/res/values/strings.xml
- android/app/src/test/java/com/mulberry/ody/fake/FakeMeetingRepository.kt
close #639 
<br>
<br>
[Screen_recording_20241004_162357.webm](https://github.com/user-attachments/assets/d56f6b56-1756-44f9-89cf-e0bf589fb7cc)
<br>
> feat: 에러 메시지 구체화

- android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/join/mapper/JoinRequestMapper.kt
- android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/meeting/mapper/MeetingRequestMapper.kt
- android/app/src/main/java/com/mulberry/ody/data/remote/core/repository/DefaultMeetingRepository.kt
> refactor: 좌표 자르는 compress 함수 삭제

- android/app/src/main/java/com/mulberry/ody/presentation/notification/NotificationHelper.kt
close #681 
<br>
<br>
<br>
코드 보다가 개선하면 좋을 부분들이 보여서 아주 조금 수정해봤어요~
> refactor: NotificationHelper 리팩터링

- backend/src/test/java/com/ody/auth/controller/AuthControllerTest.java
- backend/src/test/java/com/ody/common/BaseControllerTest.java
- backend/src/test/java/com/ody/common/BaseServiceTest.java
- backend/src/test/java/com/ody/common/DtoGenerator.java
- backend/src/test/java/com/ody/common/FixtureGenerator.java
- backend/src/test/java/com/ody/common/mapper/TimeSerializerTest.java
- backend/src/test/java/com/ody/eta/service/EtaServiceTest.java
- backend/src/test/java/com/ody/mate/service/MateServiceTest.java
- backend/src/test/java/com/ody/meeting/controller/MeetingControllerTest.java
- backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
- backend/src/test/java/com/ody/member/service/MemberServiceTest.java
- backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> test: test에 generator를 사용하도록 변경

- android/app/build.gradle.kts
> release: 안드로이드 1.1.1 출시

- .github/workflows/android-ci-dev.yml
close #710
<br>
<br>
<br>
#706 CI 통과되고 있지 않아 CI이슈인가 싶어 PR 올려봅니다 😭
> chore: android ci 빌드 전 clean 추가

- android/app/src/main/res/values/strings.xml
> design: 재촉 알림 메시지 수정

- backend/src/main/java/com/ody/common/domain/BaseEntity.java
- backend/src/main/java/com/ody/eta/domain/Eta.java
- backend/src/main/java/com/ody/mate/domain/Mate.java
- backend/src/main/java/com/ody/member/domain/Member.java
- backend/src/main/java/com/ody/notification/domain/Notification.java
- backend/src/main/java/com/ody/notification/repository/NotificationRepository.java
- backend/src/main/java/com/ody/notification/service/NotificationService.java
- backend/src/main/resources/db/migration/V5__alter__timestamp__set-nano.sql
- backend/src/test/java/com/ody/common/FixtureGenerator.java
- backend/src/test/java/com/ody/notification/repository/NotificationRepositoryTest.java
- backend/src/test/java/com/ody/notification/service/NotificationServiceTest.java
> feat: revert 코드 복구를 위한 #739 revert

- android/app/src/main/java/com/mulberry/ody/data/local/service/EtaDashboardService.kt
- android/app/src/main/java/com/mulberry/ody/domain/apiresult/ApiResultExtensions.kt
- android/app/src/main/java/com/mulberry/ody/presentation/common/gps/GeoLocationHelper.kt
- android/app/src/main/java/com/mulberry/ody/presentation/common/gps/LocationHelper.kt
- android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModel.kt
- android/app/src/main/java/com/mulberry/ody/presentation/creation/destination/MeetingDestinationFragment.kt
- android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
- android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinViewModel.kt
- android/app/src/main/res/layout/activity_meeting_join.xml
- android/app/src/main/res/layout/fragment_meeting_destination.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/test/java/com/mulberry/ody/fake/FakeLocationHelper.kt
- android/app/src/test/java/com/mulberry/ody/presentation/creation/MeetingCreationViewModelTest.kt
- android/app/src/test/java/com/mulberry/ody/presentation/join/MeetingJoinViewModelTest.kt
close #758
<br>
<br>
https://github.com/user-attachments/assets/ad10ad50-0db2-4357-b844-62955ccc3bb2
<br>
코루틴의 withTimeout 함수를 활용해서, 위치를 3초 이상 가져오는 경우 ApiResult.Unexpected를 반환하도록 했습니다.
그리고 화면에서도 현위치를 불러올 수 없다는 스낵바를 띄우고 있어요.
> fix: 현위치 가져올 때 무한 로딩되는 버그 해결

- android/app/src/main/java/com/mulberry/ody/data/remote/thirdparty/login/kakao/KakaoLoginRepository.kt
close #766 
<br>
<br>
<br>
token이 있는지 확인하고, 가진 토큰으로 갱신이 되는지 확인하고 자동 로그인을 진행하도록 바꾸었습니다.
> fix: refresh token 만료 시에도 자동 로그인 하는 문제

- android/app/src/main/res/values/strings.xml
> design: 오디 버튼 비활성화 토스트 메시지 변경

- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/common.yml
close #817 
<br>
- 이유
병합된 과정에서 이전 비밀번호를 사용한 새로운 값이 들어옴.
충돌 과정에서 이전 비밀번호로 암호화된 값이 덮어씌워졌음
<br>
<br>
> chore: jayspt 비밀번호 충돌 해결

- backend/src/main/resources/common.yml
close #819 
<br>
노션에 잘못된 api-key가 문서화 되어 있었어요.
+) 추가적으로, 모든 암호화 되어있는 key들 확인 했습니다.
+) 노션 문서도 업데이트 했습니다
<br>
<br>
> fix: RouteClient 호출시 key 오류로 인한 에러

- android/app/src/main/res/layout/activity_meetings.xml
> design: 약속 생성/참여 플로팅 버튼 margin 제거

- README.md
> docs: android 리드미 링크 수정

- android/app/src/main/java/com/mulberry/ody/presentation/common/CommonBindingAdapter.kt
- android/app/src/main/java/com/mulberry/ody/presentation/common/listener/SingleClickListener.kt
- android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardBindingAdapter.kt
- android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardGuideFirstFragment.kt
- android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardGuideSecondFragment.kt
- android/app/src/main/java/com/mulberry/ody/presentation/setting/withdrawal/WithDrawalDialog.kt
- android/app/src/main/res/layout-sw1080dp/activity_login.xml
- android/app/src/main/res/layout-sw720dp/activity_login.xml
- android/app/src/main/res/layout/activity_invite_code.xml
- android/app/src/main/res/layout/activity_login.xml
- android/app/src/main/res/layout/activity_meeting_creation.xml
- android/app/src/main/res/layout/activity_meeting_join.xml
- android/app/src/main/res/layout/activity_meetings.xml
- android/app/src/main/res/layout/dialog_exit_meeting_room.xml
- android/app/src/main/res/layout/fragment_address_search.xml
- android/app/src/main/res/layout/fragment_meeting_destination.xml
- android/app/src/main/res/layout/fragment_meeting_name.xml
- android/app/src/main/res/layout/fragment_notification_log.xml
- android/app/src/main/res/layout/item_address_search.xml
- android/app/src/main/res/layout/item_meeting_catalog.xml
- android/app/src/main/res/layout/item_setting.xml
- android/app/src/main/res/layout/layout_navigate_to_eta.xml
- android/app/src/main/res/layout/toolbar_address_search.xml
- android/app/src/main/res/layout/toolbar_back.xml
- android/app/src/main/res/layout/toolbar_eta_dashboard.xml
- android/app/src/main/res/layout/toolbar_intro.xml
- android/app/src/main/res/layout/toolbar_notification_log.xml
- android/app/src/main/res/layout/toolbar_setting.xml
close #280 
<br>
<br>
아래 코드는 예전 방식
```
@BindingAdapter("onSingleClick")
fun View.setOnSingleClickListener(onSingleClick: () -> Unit) {
val singleClickListener = SingleClickListener { onSingleClick() }
this.setOnClickListener(singleClickListener)
}
```
activity_invite_code.xml 안에서
위와 같이 한 위젯에만 onSingleClick 속성 전달 시 컴파일 성공
---
위와 같이 두 위젯에 onSingleClick 속성 적용시 컴파일 실패
---
위와 같이 한 위젯은 람다 한 위젯은 참조 방식으로 전달 시 컴파일 성공
---
현재는 아래와 같이 바인딩 어댑터를 만들어서 성공
```
@BindingAdapter("onSingleClick")
fun View.setOnSingleClickListener(onSingleClick: View.OnClickListener) {
val singleClickListener = SingleClickListener { onSingleClick.onClick(this) }
setOnClickListener(singleClickListener)
}
```
<br>
이유가 뭔지 파악하려고 하는데 다른 분들도 같이 고민해주시면 좋을 것 같아요! 감사합니다!
> refactor: single click listener로 리팩터링

- android/app/build.gradle.kts
> release: 안드로이드 1.2.2 cd 테스트 배포

- .github/workflows/android-cd-dev.yml
close #862
<br>
<br>
<br>
실화야? 하..
URL -> URI 하나 추가요
이 정도면 병이다 병
> fix: 안드로이드 cd 배포 시 개인정보 페이지 열리지 않는 문제 수정

- README.md
- android/app/src/main/java/com/mulberry/ody/presentation/LifecycleExtensions.kt
- android/app/src/main/java/com/mulberry/ody/presentation/address/AddressSearchFragment.kt
- android/app/src/main/java/com/mulberry/ody/presentation/creation/MeetingCreationActivity.kt
- android/app/src/main/java/com/mulberry/ody/presentation/creation/date/MeetingDateFragment.kt
- android/app/src/main/java/com/mulberry/ody/presentation/creation/destination/MeetingDestinationFragment.kt
- android/app/src/main/java/com/mulberry/ody/presentation/creation/time/MeetingTimeFragment.kt
- android/app/src/main/java/com/mulberry/ody/presentation/invitecode/InviteCodeActivity.kt
- android/app/src/main/java/com/mulberry/ody/presentation/join/MeetingJoinActivity.kt
- android/app/src/main/java/com/mulberry/ody/presentation/login/LoginActivity.kt
- android/app/src/main/java/com/mulberry/ody/presentation/meetings/MeetingsActivity.kt
- android/app/src/main/java/com/mulberry/ody/presentation/room/MeetingRoomActivity.kt
- android/app/src/main/java/com/mulberry/ody/presentation/room/etadashboard/EtaDashboardFragment.kt
- android/app/src/main/java/com/mulberry/ody/presentation/room/log/ExitMeetingRoomDialog.kt
- android/app/src/main/java/com/mulberry/ody/presentation/room/log/NotificationLogFragment.kt
- android/app/src/main/java/com/mulberry/ody/presentation/setting/SettingActivity.kt
> refactor: repeatOnLifecycle 확장 함수 수정

- android/app/src/main/java/com/mulberry/ody/data/remote/core/entity/notification/mapper/NotificationLogsResponseMapper.kt
> design: 나가기 로그 타입 문자열 수정

- backend/src/main/resources/db/migration/V8__drop_unique_meeting_and_member.sql
- backend/src/main/resources/db/migration/V9__add_unique_meeting_and_member_and_deleted_at.sql
close #891
<br>
#880 에서 SQL 파일을 누락해서 DB에는 반영이 안 되었네요!
해당 PR 머지 후 재배포하겠습니다 
<br>
<br>
> chore: 나갔던 약속에 재참여가 되지 않는 문제 개선 SQL 추가

- .github/workflows/android-cd-dev.yml
- .github/workflows/backend-cd-prod.yml
close #896
<br>
main과 develop 싱크 차이로 배포 때마다 conflict가 나서 싱크 맞춥니다
단순 코드 일치 PR이라 선착순으로 두 분 approve 해주시면 머지하겠습니다
<br>
<br>
> chore: matching main and develop cd scripts

- .github/workflows/backend-cd-dev.yml
close #939
<br>
<br>
<br>
<br>
원래 이걸 콜리 PR에 커밋 끼워넣기 하려고 했는데, 음 당연히 안 되는 걸 끼워 넣으려고 했어요~ 제가 요즘 정신이 없네요 죄송합니다 ^^;
> chore: 개발 서버 cd 체크아웃 브랜치 복구

- backend/src/main/java/com/ody/mate/domain/Mate.java
- backend/src/main/java/com/ody/meeting/controller/MeetingController.java
- backend/src/main/java/com/ody/meeting/controller/MeetingControllerSwagger.java
- backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponseV1.java
- backend/src/main/java/com/ody/meeting/dto/response/MeetingWithMatesResponseV2.java
- backend/src/main/java/com/ody/meeting/service/MeetingService.java
- backend/src/test/java/com/ody/meeting/service/MeetingServiceTest.java
close #956
<br>
- 약속 단건조회 응답 데이터에 출발시각과 소요시간을 추가로 반환합니다.
<br>
<br>
> refactor: 약속 단건 조회 api v2 구현

- backend/src/main/resources/common.yml
close #985
<br>
IOS 측에서 패키지명을 변경하여 새로운 인증 정보로 교체합니다!
<br>
<br>
> chore: Apple 인증 정보 교체
